"""Export the canonical Pydantic ThreadItem schema as a compact TypeScript union."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.services.thread_items import EVENT_THREAD_ITEM_TYPES, THREAD_ITEM_ADAPTER


def _reference_name(schema: dict[str, Any]) -> str | None:
    reference = schema.get("$ref")
    return str(reference).rsplit("/", 1)[-1] if reference else None


def _typescript_type(schema: dict[str, Any]) -> str:
    reference = _reference_name(schema)
    if reference:
        return reference
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        values = list(dict.fromkeys(_typescript_type(item) for item in schema["anyOf"]))
        return " | ".join(values)
    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _typescript_type(dict(schema.get("items") or {}))
        return f"Array<{item_type}>"
    if schema_type == "object":
        properties = dict(schema.get("properties") or {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required") or [])
        members = []
        for name, value in properties.items():
            marker = "" if _is_emitted(name, value, required) else "?"
            members.append(f"{name}{marker}: {_typescript_type(value)}")
        return "{ " + "; ".join(members) + " }"
    return "unknown"


def _is_emitted(name: str, schema: dict[str, Any], required: set[str]) -> bool:
    return name in required or ("default" in schema and schema.get("default") is not None)


def _interface(name: str, schema: dict[str, Any], *, extends: str | None = None) -> str:
    properties = dict(schema.get("properties") or {})
    required = set(schema.get("required") or [])
    lines = [f"export interface {name}{f' extends {extends}' if extends else ''} {{"]
    for property_name, property_schema in properties.items():
        marker = "" if _is_emitted(property_name, property_schema, required) else "?"
        lines.append(f"  {property_name}{marker}: {_typescript_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def render_typescript_contract() -> str:
    schema = THREAD_ITEM_ADAPTER.json_schema()
    definitions: dict[str, dict[str, Any]] = dict(schema["$defs"])
    root_items = [_reference_name(item) for item in schema.get("oneOf", []) if _reference_name(item)]
    if not root_items:
        raise RuntimeError("ThreadItem JSON schema is missing its discriminated oneOf union")

    first_item = definitions[root_items[0]]
    base_schema = {
        "properties": {
            name: value
            for name, value in dict(first_item["properties"]).items()
            if name not in {"item_type", "item_data"}
        },
        "required": [name for name in first_item.get("required", []) if name not in {"item_type", "item_data"}],
    }

    blocks = [
        "// GENERATED by `python -m app.scripts.export_thread_items`; do not edit by hand.",
        "// Source of truth: backend/app/services/thread_items.py (Pydantic discriminated union).",
        "",
        "export type ThreadItemStatus = 'running' | 'waiting_user' | 'succeeded' | 'failed' | 'cancelled';",
        "",
        _interface("ThreadItemBase", base_schema),
    ]

    for definition_name in sorted(name for name in definitions if name.endswith("ItemData")):
        blocks.extend(["", _interface(definition_name, definitions[definition_name])])

    for item_name in root_items:
        item_schema = definitions[item_name]
        variant_schema = {
            "properties": {
                "item_type": item_schema["properties"]["item_type"],
                "item_data": item_schema["properties"]["item_data"],
            },
            "required": ["item_type", "item_data"],
        }
        blocks.extend(["", _interface(item_name, variant_schema, extends="ThreadItemBase")])

    blocks.extend(
        [
            "",
            "export type ThreadItem =",
            *(f"  | {name}" for name in root_items),
            ";",
            "",
            "export type ThreadItemType = ThreadItem['item_type'];",
            "",
            "export const LEGACY_THREAD_ITEM_TYPE_MAP: Readonly<Record<string, ThreadItemType>> = "
            + json.dumps(EVENT_THREAD_ITEM_TYPES, indent=2, sort_keys=True)
            + " as const;",
            "",
        ]
    )
    return "\n".join(blocks)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_typescript_contract(), encoding="utf-8")


if __name__ == "__main__":
    main()
