// GENERATED by `python -m app.scripts.export_thread_items`; do not edit by hand.
// Source of truth: backend/app/services/thread_items.py (Pydantic discriminated union).

export type ThreadItemStatus = 'running' | 'waiting_user' | 'succeeded' | 'failed' | 'cancelled';

export interface ThreadItemBase {
  schema: "hive.thread_item.v1";
  schema_version: number;
  id: string;
  sequence: number;
  thread_id?: string | null;
  session_id?: string | null;
  run_id?: string | null;
  message_id?: string | null;
  parent_event_id?: string | null;
  root_session_id?: string | null;
  parent_session_id?: string | null;
  turn_id?: string | null;
  causation_id?: string | null;
  correlation_id?: string | null;
  item_status: "running" | "waiting_user" | "succeeded" | "failed" | "cancelled";
  actor_type: string;
  event_type: string;
  type: string;
  role: string;
  visibility_scope: string;
  listed_surface: string;
  content: string;
  parts?: Array<Record<string, unknown>>;
  metadata?: Record<string, unknown>;
  created_at?: string | null;
  completed_at?: string | null;
  evidence_refs?: Array<Record<string, unknown>>;
  audience: "user" | "operator";
  user_summary: string;
  user_action?: UserAction | null;
  operator_details?: OperatorDetails | null;
}

export interface ApprovalDecisionItemData {
  permission_request_id?: string | null;
  action?: string | null;
  decision_reason?: string | null;
  approver_id?: string | null;
}

export interface ApprovalRequestItemData {
  permission_request_id: string;
  tool_name?: string | null;
  tool_display_name?: string | null;
  arguments?: Record<string, unknown>;
  capability?: string | null;
  security_zone?: string | null;
  permission_mode?: string | null;
  decision_reason?: string | null;
  risk_class?: string | null;
  confirmation_kind?: string | null;
  expires_at?: string | null;
  allow_session_allowed: boolean;
  destructive: boolean;
}

export interface ArtifactItemData {
  artifact_id?: string | null;
  path?: string | null;
  revision_id?: string | null;
  action?: string | null;
}

export interface BoundaryItemData {
  phase?: string | null;
  reason?: string | null;
}

export interface CompactionItemData {
  original_message_count?: number | null;
  kept_message_count?: number | null;
  continuity_sections_injected?: Array<string>;
}

export interface ErrorItemData {
  code?: string | null;
  reason?: string | null;
  retryable: boolean;
  retry_reason?: string | null;
}

export interface EventItemData {
  event_type: string;
  title?: string | null;
  runtime_task_id?: string | null;
  reason?: string | null;
}

export interface MessageItemData {
  sender_name?: string | null;
  file_name?: string | null;
}

export interface OperatorDetails {
  item_data?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  evidence_refs?: Array<Record<string, unknown>>;
  links?: Record<string, unknown>;
}

export interface PlanItemData {
  plan_id?: string | null;
  plan_version?: number | null;
  plan_hash?: string | null;
  phase?: string | null;
}

export interface ReasoningItemData {
  signature?: string | null;
}

export interface SubagentItemData {
  runtime_task_id?: string | null;
  child_session_id?: string | null;
  parent_session_id?: string | null;
  target_agent_name?: string | null;
}

export interface ToolCallItemData {
  tool_name?: string | null;
  tool_call_id?: string | null;
  arguments?: Record<string, unknown>;
  risk_class?: string | null;
}

export interface ToolResultItemData {
  event_type: string;
  tool_name?: string | null;
  tool_call_id?: string | null;
  success: boolean;
}

export interface UserAction {
  kind: string;
  token?: string | null;
  label: string;
  expires_at?: string | null;
  impact?: string | null;
  details?: Array<Record<string, unknown>>;
}

export interface WorkflowItemData {
  workflow_run_id?: string | null;
  workflow_step_id?: string | null;
  runtime_task_id?: string | null;
  label?: string | null;
}

export interface UserMessageThreadItem extends ThreadItemBase {
  item_type: "user_message";
  item_data: MessageItemData;
}

export interface AgentMessageThreadItem extends ThreadItemBase {
  item_type: "agent_message";
  item_data: MessageItemData;
}

export interface ReasoningThreadItem extends ThreadItemBase {
  item_type: "reasoning";
  item_data: ReasoningItemData;
}

export interface ToolCallThreadItem extends ThreadItemBase {
  item_type: "tool_call";
  item_data: ToolCallItemData;
}

export interface ToolResultThreadItem extends ThreadItemBase {
  item_type: "tool_result";
  item_data: ToolResultItemData;
}

export interface ApprovalRequestThreadItem extends ThreadItemBase {
  item_type: "approval_request";
  item_data: ApprovalRequestItemData;
}

export interface ApprovalDecisionThreadItem extends ThreadItemBase {
  item_type: "approval_decision";
  item_data: ApprovalDecisionItemData;
}

export interface PlanThreadItem extends ThreadItemBase {
  item_type: "plan";
  item_data: PlanItemData;
}

export interface WorkflowThreadItem extends ThreadItemBase {
  item_type: "workflow_activity";
  item_data: WorkflowItemData;
}

export interface SubagentThreadItem extends ThreadItemBase {
  item_type: "subagent_activity";
  item_data: SubagentItemData;
}

export interface CompactionThreadItem extends ThreadItemBase {
  item_type: "context_compaction";
  item_data: CompactionItemData;
}

export interface ArtifactThreadItem extends ThreadItemBase {
  item_type: "artifact";
  item_data: ArtifactItemData;
}

export interface BoundaryThreadItem extends ThreadItemBase {
  item_type: "boundary";
  item_data: BoundaryItemData;
}

export interface ErrorThreadItem extends ThreadItemBase {
  item_type: "error";
  item_data: ErrorItemData;
}

export interface EventThreadItem extends ThreadItemBase {
  item_type: "event";
  item_data: EventItemData;
}

export type ThreadItem =
  | UserMessageThreadItem
  | AgentMessageThreadItem
  | ReasoningThreadItem
  | ToolCallThreadItem
  | ToolResultThreadItem
  | ApprovalRequestThreadItem
  | ApprovalDecisionThreadItem
  | PlanThreadItem
  | WorkflowThreadItem
  | SubagentThreadItem
  | CompactionThreadItem
  | ArtifactThreadItem
  | BoundaryThreadItem
  | ErrorThreadItem
  | EventThreadItem
;

export type ThreadItemType = ThreadItem['item_type'];

export const LEGACY_THREAD_ITEM_TYPE_MAP: Readonly<Record<string, ThreadItemType>> = {
  "advanced_plan": "plan",
  "agent_task_notification": "subagent_activity",
  "approval.resolved": "approval_decision",
  "approval.resolved_via_feishu": "approval_decision",
  "approval_request": "approval_request",
  "artifact_delivery": "artifact",
  "artifact_update": "artifact",
  "assistant_message": "agent_message",
  "child_session": "subagent_activity",
  "circuit_break": "error",
  "delegation_run": "subagent_activity",
  "denial": "error",
  "done": "boundary",
  "dynamic_workflow": "workflow_activity",
  "error": "error",
  "expired": "error",
  "file_changes": "artifact",
  "hard_stopped": "error",
  "loop": "error",
  "member_idle": "subagent_activity",
  "member_message_queued": "subagent_activity",
  "member_message_rejected": "subagent_activity",
  "member_run_started": "subagent_activity",
  "member_spawned": "subagent_activity",
  "memory_context_degraded": "error",
  "memory_context_unavailable": "error",
  "permission": "approval_request",
  "permission_profile_updated": "approval_decision",
  "permission_request": "approval_request",
  "permission_resolved": "approval_decision",
  "phase": "boundary",
  "plan": "plan",
  "plan_confirmed": "plan",
  "plan_failed": "plan",
  "quota_exceeded": "error",
  "reasoning": "reasoning",
  "run_cancelled": "boundary",
  "run_completed": "boundary",
  "run_queued": "boundary",
  "run_started": "boundary",
  "runtime_action_blocked": "error",
  "runtime_action_failed": "error",
  "segment_boundary": "boundary",
  "session_branch": "boundary",
  "session_clear": "boundary",
  "session_compact": "context_compaction",
  "session_permission_decision": "approval_decision",
  "session_permission_expired": "approval_decision",
  "session_permission_request": "approval_request",
  "session_rewind": "boundary",
  "session_workspace_rewind": "boundary",
  "subagent": "subagent_activity",
  "subagent_task_completed": "subagent_activity",
  "subagent_task_started": "subagent_activity",
  "summary_turn": "context_compaction",
  "team_member": "subagent_activity",
  "thinking": "reasoning",
  "tool_call": "tool_call",
  "tool_failure": "tool_result",
  "tool_result": "tool_result",
  "tool_success": "tool_result",
  "turn_steered": "boundary",
  "user_message": "user_message",
  "workflow_completed": "workflow_activity",
  "workflow_failed": "workflow_activity",
  "workflow_run": "workflow_activity",
  "workflow_started": "workflow_activity",
  "workflow_step": "workflow_activity"
} as const;
