"""J2 red tests: growth report (eval-system-spec §2.1).

The growth report answers "is this agent actually getting stronger?" from
production evidence only — pure SQL/file counting, ZERO LLM (counting is
mechanical; interpretation belongs to heartbeat/dream reflection, which reads
the report as input). v1 metrics:

1. failure-mode recurrence / avoidance (per self.md failure-mode id, detected
   from T2 labels ``<failure_signal ref outcome>`` rows in t2_label_axes);
2. knowledge reuse (reverse-reference counts from the C8 index);
3. owner feedback polarity trend (session_feedback rows);
4. rework rate trend (labels rework axis) + task volume (invocation_spans).

Artifact: per-agent ``memory/control/growth_report.md`` plus an append-only
``growth_metrics_history.jsonl`` snapshot (same pattern as the debt ledger),
generated by the heartbeat maintenance batch; surfaced through the existing
observability read model — zero new frontend.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import uuid4

import pytest


NOW = datetime(2026, 7, 2, 12, 0, 0, tzinfo=UTC)


def _mem_dir(tmp_path: Path, agent_id) -> Path:
    return tmp_path / str(agent_id) / "memory"


def _write_self_md(tmp_path: Path, agent_id) -> None:
    self_dir = _mem_dir(tmp_path, agent_id) / "self"
    self_dir.mkdir(parents=True, exist_ok=True)
    (self_dir / "self.md").write_text(
        "## 能力\n\n### 深度研究 — 熟练\n<!-- id: cap-deep-research -->\n拆解与检索。\n- 证据: t2-a1b2\n\n"
        "## 失败模式\n\n### 需求含糊时爱猜 — active\n<!-- id: fm-guessing -->\n- 状态: active\n- 证据: t2-a1b2\n\n"
        "### 长任务忘推进 — 规避中\n<!-- id: fm-stall -->\n- 状态: 规避中\n- 证据: t2-c3d4\n",
        encoding="utf-8",
    )


def _write_package(
    tmp_path: Path,
    agent_id,
    *,
    segment_id: str,
    created_at: datetime,
    failure_signals: str = "",
    rework: bool = False,
) -> None:
    package_dir = _mem_dir(tmp_path, agent_id) / "t2" / "sessions" / "sess-1" / "segments" / segment_id
    package_dir.mkdir(parents=True, exist_ok=True)
    package_id = f"t2pkg-{segment_id}"
    (package_dir / "manifest.json").write_text(
        json.dumps(
            {
                "schema_version": "t2.segment-package.manifest.v1",
                "package_id": package_id,
                "package_status": "absorbed",
                "session_id": "sess-1",
                "t0_segment_id": segment_id,
                "created_at": created_at.isoformat(),
            }
        ),
        encoding="utf-8",
    )
    rework_block = '<rework present="true">重做了上一轮报告结构。</rework>' if rework else ""
    (package_dir / "labels.md").write_text(
        f"""<t2_labels schema_version="t2.labels.v1" package_id="{package_id}">
  <continuity_state>standalone</continuity_state>
  <failure_signals>{failure_signals}</failure_signals>
  {rework_block}
</t2_labels>""",
        encoding="utf-8",
    )
    (package_dir / "review.md").write_text(
        f'<t2_review schema_version="t2.review.v1" package_id="{package_id}">'
        "<decision>approved</decision><allowed_next>t3_intake</allowed_next></t2_review>",
        encoding="utf-8",
    )


def _seed_agent(tmp_path: Path, agent_id) -> None:
    from app.memory.reference_index import rebuild_reference_index

    _write_self_md(tmp_path, agent_id)
    _write_package(
        tmp_path,
        agent_id,
        segment_id="seg-1",
        created_at=NOW - timedelta(days=10),
        failure_signals='<failure_signal ref="fm-guessing" outcome="recurred">又猜了需求。</failure_signal>',
        rework=True,
    )
    _write_package(
        tmp_path,
        agent_id,
        segment_id="seg-2",
        created_at=NOW - timedelta(days=2),
        failure_signals=(
            '<failure_signal ref="fm-guessing" outcome="avoided">这次先澄清再动手。</failure_signal>'
            '<failure_signal ref="fm-stall" outcome="avoided">ledger 驱动推进。</failure_signal>'
        ),
    )
    # knowledge page citing seg-1 evidence — reuse signal via reverse refs
    knowledge = _mem_dir(tmp_path, agent_id) / "knowledge"
    knowledge.mkdir(parents=True, exist_ok=True)
    (knowledge / "l2-rollup.md").write_text(
        "---\ntitle: L2 Rollup\nstatus: active\n---\n## Current Claim\n链下扩容。\n"
        "## Evidence\nt2-seg-1\n\n## Relations\n- is_a [[k:scaling]]\n",
        encoding="utf-8",
    )
    rebuild_reference_index(agent_id=agent_id, data_root=tmp_path)


def test_growth_metrics_failure_modes_and_rework(tmp_path: Path) -> None:
    from app.services.growth_report import build_growth_metrics

    agent_id = uuid4()
    _seed_agent(tmp_path, agent_id)

    metrics = build_growth_metrics(data_root=tmp_path, agent_id=agent_id, now=NOW)

    fm = {row["id"]: row for row in metrics["failure_modes"]}
    assert fm["fm-guessing"]["recurred"] == 1
    assert fm["fm-guessing"]["avoided"] == 1
    assert fm["fm-guessing"]["status"] == "active"
    assert fm["fm-stall"]["recurred"] == 0
    assert fm["fm-stall"]["avoided"] == 1

    rework = metrics["rework"]
    assert rework["labeled_packages"] == 2
    assert rework["rework_packages"] == 1
    # trend buckets: the older (rework) package and the recent one land apart
    assert rework["recent_rate"] == 0.0
    assert rework["previous_rate"] == 1.0

    reuse = metrics["reuse"]
    assert reuse["knowledge_pages"] == 1
    assert reuse["total_citations"] >= 1
    assert reuse["top_cited"]


def test_growth_metrics_zero_llm_and_calm_when_empty(tmp_path: Path) -> None:
    """Empty agent: metrics report zeros, never raise — and the module must
    not import any LLM client (counting is mechanical)."""
    import app.services.growth_report as module
    from app.services.growth_report import build_growth_metrics

    agent_id = uuid4()
    _mem_dir(tmp_path, agent_id).mkdir(parents=True)

    metrics = build_growth_metrics(data_root=tmp_path, agent_id=agent_id, now=NOW)

    assert metrics["failure_modes"] == []
    assert metrics["rework"]["labeled_packages"] == 0
    assert metrics["reuse"]["knowledge_pages"] == 0
    source = Path(module.__file__).read_text(encoding="utf-8")
    assert "llm_client" not in source
    assert "create_client" not in source


@pytest.mark.asyncio
async def test_refresh_growth_report_writes_md_and_history(tmp_path: Path) -> None:
    from app.services.growth_report import refresh_growth_report

    agent_id = uuid4()
    _seed_agent(tmp_path, agent_id)

    report_path = await refresh_growth_report(data_root=tmp_path, agent_id=agent_id, db=None, now=NOW)

    assert report_path == _mem_dir(tmp_path, agent_id) / "control" / "growth_report.md"
    body = report_path.read_text(encoding="utf-8")
    assert "fm-guessing" in body
    assert "复发" in body or "recurred" in body
    assert "返工" in body or "rework" in body
    assert "引用" in body or "citation" in body

    history_path = _mem_dir(tmp_path, agent_id) / "control" / "growth_metrics_history.jsonl"
    lines = [json.loads(line) for line in history_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert len(lines) == 1
    assert lines[0]["generated_at"]

    await refresh_growth_report(data_root=tmp_path, agent_id=agent_id, db=None, now=NOW + timedelta(hours=1))
    lines = [json.loads(line) for line in history_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert len(lines) == 2


@pytest.mark.asyncio
async def test_growth_db_metrics_feedback_polarity_and_task_volume(tmp_path: Path) -> None:
    """DB-side metrics run against a real engine (no mocks of our own layer)."""
    from sqlalchemy.dialects.postgresql import JSONB
    from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
    from sqlalchemy.ext.compiler import compiles

    from app.database import Base
    from app.models import import_all_models

    import_all_models()  # register FK target tables in Base.metadata
    from app.models.invocation_span import InvocationSpan
    from app.models.session_feedback import SessionFeedbackEvent
    from app.services.growth_report import build_growth_db_metrics

    @compiles(JSONB, "sqlite")
    def _jsonb_as_json(_type, _compiler, **_kw):  # real engine, sqlite renders JSONB as JSON
        return "JSON"

    engine = create_async_engine("sqlite+aiosqlite://")
    async with engine.begin() as conn:
        await conn.run_sync(
            lambda sync_conn: Base.metadata.create_all(
                sync_conn, tables=[SessionFeedbackEvent.__table__, InvocationSpan.__table__]
            )
        )

    agent_id = uuid4()
    tenant_id = uuid4()
    async with AsyncSession(engine) as db:
        db.add(
            SessionFeedbackEvent(
                tenant_id=tenant_id,
                agent_id=agent_id,
                session_id=uuid4(),
                user_id=uuid4(),
                label="useful",
                reason="",
                created_at=NOW - timedelta(days=1),
            )
        )
        db.add(
            SessionFeedbackEvent(
                tenant_id=tenant_id,
                agent_id=agent_id,
                session_id=uuid4(),
                user_id=uuid4(),
                label="misleading",
                reason="",
                created_at=NOW - timedelta(days=20),
            )
        )
        db.add(
            InvocationSpan(
                tenant_id=tenant_id,
                agent_id=agent_id,
                trace_id=str(uuid4()),
                span_id=str(uuid4()),
                span_type="invocation",
                name="chat",
                status="ok",
                started_at=NOW - timedelta(days=1),
                duration_ms=1200.0,
            )
        )
        await db.commit()

        metrics = await build_growth_db_metrics(db=db, agent_id=agent_id, now=NOW)

    polarity = metrics["feedback_polarity"]
    assert polarity["recent"]["useful"] == 1
    assert polarity["recent"]["misleading"] == 0
    assert polarity["previous"]["misleading"] == 1
    volume = metrics["task_volume"]
    assert volume["recent_invocations"] == 1
    await engine.dispose()


def test_observability_exposes_growth(tmp_path: Path) -> None:
    from app.services.growth_report import write_growth_report_files
    from app.services.knowledge_read_model import build_memory_observability

    agent_id = uuid4()
    _seed_agent(tmp_path, agent_id)
    write_growth_report_files(
        data_root=tmp_path,
        agent_id=agent_id,
        metrics={"failure_modes": [], "rework": {}, "reuse": {}, "generated_at": NOW.isoformat()},
        report_md="# Growth Report\nok\n",
    )

    observability = build_memory_observability(tmp_path, agent_id)

    assert observability["growth"]["generated_at"] == NOW.isoformat()
    assert observability["growth"]["report_path"].endswith("memory/control/growth_report.md")


def test_heartbeat_wires_growth_report_refresh() -> None:
    import inspect

    from app.services import heartbeat

    source = inspect.getsource(heartbeat)
    assert "_run_growth_report_refresh" in source
    assert "refresh_growth_report" in source


def test_heartbeat_template_teaches_growth_report_reflection() -> None:
    template = Path("app/templates/HEARTBEAT.md").read_text(encoding="utf-8")
    assert "growth_report" in template
