"""J2 growth report — "is this agent actually getting stronger?" (eval-system-spec §2.1).

Pure SQL/file counting over production evidence, ZERO LLM: counting is
mechanical work and does not violate L1; interpretation belongs to the
heartbeat/dream reflection loop, which reads this report as input.

v1 metrics:
1. failure-mode recurrence / avoidance — per self.md failure-mode id,
   aggregated from the ``failure_mode_recurred`` / ``failure_mode_avoided``
   axes of the C8 ``t2_label_axes`` table (labels 工序 1 emits the signals);
2. knowledge reuse — reverse-reference citation counts from the C8 index;
3. owner feedback polarity trend — ``session_feedback_events`` rows;
4. rework rate trend + task volume — labels ``rework`` axis buckets and
   ``invocation_spans`` counts.

Artifacts: per-agent ``memory/control/growth_report.md`` (the thing the owner
opens) plus append-only ``memory/control/growth_metrics_history.jsonl``
snapshots (same pattern as the consolidation-debt ledger). Generated by the
heartbeat maintenance batch; surfaced through the existing memory
observability read model — zero new frontend.
"""

from __future__ import annotations

import json
import logging
import sqlite3
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

GROWTH_REPORT_RELATIVE = Path("control") / "growth_report.md"
GROWTH_HISTORY_RELATIVE = Path("control") / "growth_metrics_history.jsonl"

# Trend buckets: "recent" vs "previous" comparison windows (days). Coarse on
# purpose — the report shows direction, reflection interprets it.
TREND_WINDOW_DAYS = 7
REUSE_TOP_N = 5


def build_growth_metrics(
    *,
    data_root: Path | str,
    agent_id: uuid.UUID | str,
    now: datetime | None = None,
) -> dict[str, Any]:
    """File/SQLite-side metrics. DB-backed metrics live in
    :func:`build_growth_db_metrics` so callers without a session still get the
    memory-side picture."""
    from app.memory.plane_read import list_profile_entries
    from app.memory.reference_index import index_db_path, rebuild_reference_index

    root = Path(data_root)
    current = _now_utc(now)
    rebuild_reference_index(agent_id=agent_id, data_root=root)

    failure_status: dict[str, dict[str, str]] = {}
    for entry in list_profile_entries(root, agent_id):
        if str(entry.get("source") or "").endswith("self/self.md") and str(entry.get("id") or "").startswith("fm-"):
            body = str(entry.get("content") or "")
            status = ""
            for line in body.splitlines():
                stripped = line.strip()
                if stripped.startswith("- 状态:"):
                    status = stripped.removeprefix("- 状态:").strip()
                    break
            failure_status[str(entry["id"])] = {
                "title": str(entry.get("heading") or entry.get("preview") or entry["id"]),
                "status": status,
            }

    recurred: dict[str, int] = {}
    avoided: dict[str, int] = {}
    rework_rows: list[tuple[str, str]] = []  # (value, created_at)
    labeled_packages = 0
    db_path = index_db_path(root, agent_id)
    if db_path.exists():
        try:
            with sqlite3.connect(db_path) as conn:
                for axis, value, created_at in conn.execute("SELECT axis, value, created_at FROM t2_label_axes"):
                    axis = str(axis)
                    if axis == "failure_mode_recurred":
                        recurred[str(value)] = recurred.get(str(value), 0) + 1
                    elif axis == "failure_mode_avoided":
                        avoided[str(value)] = avoided.get(str(value), 0) + 1
                    elif axis == "rework":
                        rework_rows.append((str(value), str(created_at or "")))
                labeled_packages = int(
                    conn.execute("SELECT COUNT(DISTINCT package_ref) FROM t2_label_axes").fetchone()[0] or 0
                )
        except sqlite3.Error as exc:
            logger.warning("Growth metrics index read failed for %s: %s", agent_id, exc)

    failure_modes: list[dict[str, Any]] = []
    for mode_id in sorted({*failure_status, *recurred, *avoided}):
        info = failure_status.get(mode_id, {})
        r = recurred.get(mode_id, 0)
        a = avoided.get(mode_id, 0)
        failure_modes.append(
            {
                "id": mode_id,
                "title": info.get("title", mode_id),
                "status": info.get("status", ""),
                "recurred": r,
                "avoided": a,
                "avoidance_rate": round(a / (r + a), 2) if (r + a) else None,
            }
        )

    cutoff = current - timedelta(days=TREND_WINDOW_DAYS)
    recent_rework, previous_rework = _bucket_counts(rework_rows, cutoff)
    recent_packages, previous_packages = _bucket_package_counts(db_path, cutoff)
    rework = {
        "labeled_packages": labeled_packages,
        "rework_packages": len(rework_rows),
        "recent_rate": _rate(recent_rework, recent_packages),
        "previous_rate": _rate(previous_rework, previous_packages),
    }

    reuse = _reuse_metrics(db_path)

    ledger = _ledger_metrics(root, agent_id)

    return {
        "generated_at": current.isoformat(),
        "failure_modes": failure_modes,
        "rework": rework,
        "reuse": reuse,
        "evolution": ledger,
    }


async def build_growth_db_metrics(
    *,
    db: Any,
    agent_id: uuid.UUID | str,
    now: datetime | None = None,
) -> dict[str, Any]:
    """DB-side metrics: owner feedback polarity trend + task volume."""
    from sqlalchemy import func, select

    from app.models.invocation_span import InvocationSpan
    from app.models.session_feedback import SessionFeedbackEvent

    current = _now_utc(now)
    cutoff = current - timedelta(days=TREND_WINDOW_DAYS)
    previous_cutoff = cutoff - timedelta(days=TREND_WINDOW_DAYS * 3)

    polarity: dict[str, dict[str, int]] = {
        "recent": {"useful": 0, "misleading": 0},
        "previous": {"useful": 0, "misleading": 0},
    }
    rows = await db.execute(
        select(SessionFeedbackEvent.label, SessionFeedbackEvent.created_at).where(
            SessionFeedbackEvent.agent_id == agent_id,
            SessionFeedbackEvent.created_at >= previous_cutoff,
        )
    )
    for label, created_at in rows.all():
        bucket = "recent" if _aware(created_at) >= cutoff else "previous"
        key = str(label or "").strip().lower()
        if key in polarity[bucket]:
            polarity[bucket][key] += 1

    recent_invocations = (
        await db.execute(
            select(func.count())
            .select_from(InvocationSpan)
            .where(InvocationSpan.agent_id == agent_id, InvocationSpan.started_at >= cutoff)
        )
    ).scalar() or 0

    return {
        "feedback_polarity": polarity,
        "task_volume": {"recent_invocations": int(recent_invocations), "window_days": TREND_WINDOW_DAYS},
    }


async def refresh_growth_report(
    *,
    data_root: Path | str,
    agent_id: uuid.UUID | str,
    db: Any = None,
    now: datetime | None = None,
) -> Path:
    """Assemble metrics, render the report, persist md + history snapshot."""
    metrics = build_growth_metrics(data_root=data_root, agent_id=agent_id, now=now)
    if db is not None:
        try:
            metrics.update(await build_growth_db_metrics(db=db, agent_id=agent_id, now=now))
        except Exception as exc:  # noqa: BLE001 - DB-side metrics are additive; file-side report still lands
            logger.warning("Growth report DB metrics failed for %s: %s", agent_id, exc)
    report_md = render_growth_report_md(metrics)
    return write_growth_report_files(data_root=data_root, agent_id=agent_id, metrics=metrics, report_md=report_md)


def write_growth_report_files(
    *,
    data_root: Path | str,
    agent_id: uuid.UUID | str,
    metrics: dict[str, Any],
    report_md: str,
) -> Path:
    mem_dir = Path(data_root) / str(agent_id) / "memory"
    report_path = mem_dir / GROWTH_REPORT_RELATIVE
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report_md, encoding="utf-8")
    history_path = mem_dir / GROWTH_HISTORY_RELATIVE
    with history_path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(metrics, ensure_ascii=False, sort_keys=True) + "\n")
    return report_path


def render_growth_report_md(metrics: dict[str, Any]) -> str:
    """Deterministic markdown rendering — numbers only, no interpretation.

    The heartbeat/dream reflection reads this file and does the interpreting
    (L1: judgment belongs to the model, counting belongs to the platform)."""
    lines: list[str] = [
        "# Growth Report",
        "",
        f"- generated_at: {metrics.get('generated_at', '')}",
        "",
        "## 失败模式 复发/规避 (per self.md id)",
        "",
    ]
    failure_modes = metrics.get("failure_modes") or []
    if failure_modes:
        lines.append("| id | 标题 | 状态 | 复发 recurred | 规避 avoided | 规避率 |")
        lines.append("|---|---|---|---|---|---|")
        for mode in failure_modes:
            rate = mode.get("avoidance_rate")
            lines.append(
                f"| {mode['id']} | {mode.get('title', '')} | {mode.get('status', '')} "
                f"| {mode.get('recurred', 0)} | {mode.get('avoided', 0)} | {rate if rate is not None else '—'} |"
            )
    else:
        lines.append("(无失败模式信号)")
    lines += ["", "## 返工率 rework", ""]
    rework = metrics.get("rework") or {}
    lines.append(f"- labeled packages: {rework.get('labeled_packages', 0)}")
    lines.append(f"- rework packages: {rework.get('rework_packages', 0)}")
    lines.append(f"- recent window rate: {rework.get('recent_rate')}")
    lines.append(f"- previous rate: {rework.get('previous_rate')}")
    lines += ["", "## 知识复用 引用 citations", ""]
    reuse = metrics.get("reuse") or {}
    lines.append(f"- knowledge pages: {reuse.get('knowledge_pages', 0)}")
    lines.append(f"- total citations: {reuse.get('total_citations', 0)}")
    for item in reuse.get("top_cited") or []:
        lines.append(f"  - {item['ref']}: {item['count']}")
    polarity = metrics.get("feedback_polarity")
    if polarity:
        lines += ["", "## Owner 反馈极性", ""]
        for bucket in ("recent", "previous"):
            counts = polarity.get(bucket) or {}
            lines.append(f"- {bucket}: useful={counts.get('useful', 0)} misleading={counts.get('misleading', 0)}")
    volume = metrics.get("task_volume")
    if volume:
        lines += ["", "## 任务量", ""]
        lines.append(
            f"- invocations in last {volume.get('window_days', TREND_WINDOW_DAYS)}d: "
            f"{volume.get('recent_invocations', 0)}"
        )
    evolution = metrics.get("evolution") or {}
    lines += ["", "## 能力演化 (evolution ledger)", ""]
    lines.append(f"- promotion decisions: {evolution.get('promotions', 0)}")
    lines.append(f"- rollbacks: {evolution.get('rollbacks', 0)}")
    lines.append("")
    return "\n".join(lines)


def _reuse_metrics(db_path: Path) -> dict[str, Any]:
    pages = 0
    total = 0
    top: list[dict[str, Any]] = []
    if db_path.exists():
        try:
            with sqlite3.connect(db_path) as conn:
                pages = int(
                    conn.execute(
                        "SELECT COUNT(*) FROM id_resolution WHERE kind IN ('knowledge', 'milestone')"
                    ).fetchone()[0]
                    or 0
                )
                rows = conn.execute(
                    "SELECT source_ref, COUNT(DISTINCT referrer) AS c FROM refs"
                    " GROUP BY source_ref ORDER BY c DESC, source_ref LIMIT ?",
                    (REUSE_TOP_N,),
                ).fetchall()
                top = [{"ref": str(ref), "count": int(count)} for ref, count in rows]
                total = int(conn.execute("SELECT COUNT(*) FROM refs").fetchone()[0] or 0)
        except sqlite3.Error as exc:
            logger.warning("Growth reuse metrics read failed: %s", exc)
    return {"knowledge_pages": pages, "total_citations": total, "top_cited": top}


def _ledger_metrics(root: Path, agent_id: uuid.UUID | str) -> dict[str, int]:
    ledger_path = root / str(agent_id) / "evolution_ledger.jsonl"
    promotions = 0
    rollbacks = 0
    if ledger_path.exists():
        try:
            for line in ledger_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except ValueError:
                    continue
                event = str(record.get("event") or "")
                if event == "promotion_decision":
                    promotions += 1
                elif "rollback" in event:
                    rollbacks += 1
        except OSError as exc:
            logger.warning("Growth ledger read failed for %s: %s", agent_id, exc)
    return {"promotions": promotions, "rollbacks": rollbacks}


def _bucket_counts(rows: list[tuple[str, str]], cutoff: datetime) -> tuple[int, int]:
    recent = 0
    previous = 0
    for _value, created_at in rows:
        stamp = _parse_dt(created_at)
        if stamp is None or stamp >= cutoff:
            recent += 1
        else:
            previous += 1
    return recent, previous


def _bucket_package_counts(db_path: Path, cutoff: datetime) -> tuple[int, int]:
    recent = 0
    previous = 0
    if not db_path.exists():
        return 0, 0
    try:
        with sqlite3.connect(db_path) as conn:
            rows = conn.execute("SELECT DISTINCT package_ref, created_at FROM t2_label_axes").fetchall()
    except sqlite3.Error:
        return 0, 0
    for _ref, created_at in rows:
        stamp = _parse_dt(str(created_at or ""))
        if stamp is None or stamp >= cutoff:
            recent += 1
        else:
            previous += 1
    return recent, previous


def _rate(count: int, denominator: int) -> float | None:
    if denominator <= 0:
        return None
    return round(count / denominator, 2)


def _parse_dt(raw: str) -> datetime | None:
    text = (raw or "").strip()
    if not text:
        return None
    try:
        return _aware(datetime.fromisoformat(text.replace("Z", "+00:00")))
    except ValueError:
        return None


def _aware(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _now_utc(now: datetime | None) -> datetime:
    return _aware(now) if now else datetime.now(UTC)
