"""Company Knowledge and Ontology authority, recovery, and strict tenant RLS.

Revision ID: company_knowledge_closed_loop_0724
Revises: im_unverified_transport_0719
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "company_knowledge_closed_loop_0724"
down_revision: str | None = "im_unverified_transport_0719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES: tuple[str, ...] = (
    "company_knowledge_source_contracts",
    "company_knowledge_sources",
    "company_knowledge_evidence",
    "company_knowledge_proposals",
    "company_knowledge_reviews",
    "company_knowledge_publications",
    "company_knowledge_events",
    "company_knowledge_outbox",
    "company_ontology_packages",
    "company_ontology_package_versions",
    "company_ontology_package_installations",
    "company_ontology_activations",
    "company_ontology_curation_runs",
    "company_ontology_releases",
    "company_ontology_object_types",
    "company_ontology_property_types",
    "company_ontology_link_types",
    "company_ontology_event_types",
    "company_ontology_rule_definitions",
    "company_ontology_action_types",
    "company_ontology_objects",
    "company_ontology_object_identities",
    "company_ontology_assertions",
    "company_ontology_links",
    "company_ontology_events",
    "company_ontology_evidence_bindings",
    "company_ontology_release_items",
)


def _enable_strict_tenant_rls(table: str) -> None:
    policy = f"tenant_isolation_{table}"
    predicate = (
        "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
        "OR current_setting('app.rls_bypass', true) = 'on'"
    )
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
    op.execute(f'CREATE POLICY "{policy}" ON "{table}" USING ({predicate}) WITH CHECK ({predicate})')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_knowledge_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("accountable_user_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("policy_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_id", sa.String(length=300), nullable=False),
        sa.Column("request_id", sa.String(length=300), nullable=True),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["accountable_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_company_knowledge_event_idempotency"),
    )
    op.create_index(
        "ix_company_knowledge_event_stream",
        "company_knowledge_events",
        ["tenant_id", "resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_company_knowledge_event_trace",
        "company_knowledge_events",
        ["tenant_id", "trace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_events_event_type"), "company_knowledge_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_events_tenant_id"), "company_knowledge_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_knowledge_source_contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_kind", sa.String(length=50), nullable=False),
        sa.Column("provider_kind", sa.String(length=80), nullable=False),
        sa.Column("stable_source_id", sa.String(length=300), nullable=False),
        sa.Column("owner_principal_ref", sa.String(length=300), nullable=False),
        sa.Column("accountable_steward_ref", sa.String(length=300), nullable=False),
        sa.Column("connection_ref", sa.String(length=512), nullable=True),
        sa.Column("schema_ref", sa.String(length=512), nullable=True),
        sa.Column("schema_version", sa.String(length=120), nullable=True),
        sa.Column("identity_keys_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("relation_keys_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ingest_mode", sa.String(length=30), nullable=False),
        sa.Column("cursor_kind", sa.String(length=80), nullable=True),
        sa.Column("cursor_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("watermark_field", sa.String(length=300), nullable=True),
        sa.Column("temporal_mapping_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_acl_mapping_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("default_sensitivity", sa.String(length=30), server_default="PL1_public", nullable=False),
        sa.Column("export_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retention_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("legal_hold_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_namespaces_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("precedence_policy_ref", sa.String(length=512), nullable=True),
        sa.Column("acceptance_suite_ref", sa.String(length=512), nullable=True),
        sa.Column("idempotency_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contract_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_by_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "default_sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_knowledge_source_contract_sensitivity",
        ),
        sa.CheckConstraint(
            "ingest_mode IN ('manual','snapshot','incremental','cdc','webhook','reference')",
            name="ck_company_knowledge_source_contract_ingest_mode",
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','retired','blocked_drift')", name="ck_company_knowledge_source_contract_status"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "stable_source_id", "version", name="uq_company_knowledge_source_contract_version"
        ),
    )
    op.create_index(
        "ix_company_knowledge_source_contract_active",
        "company_knowledge_source_contracts",
        ["tenant_id", "stable_source_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_company_knowledge_source_contracts_contract_hash"),
        "company_knowledge_source_contracts",
        ["contract_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_source_contracts_source_kind"),
        "company_knowledge_source_contracts",
        ["source_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_source_contracts_status"),
        "company_knowledge_source_contracts",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_source_contracts_tenant_id"),
        "company_knowledge_source_contracts",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_key", sa.String(length=240), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("publisher", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('available','retired','blocked')", name="ck_company_ontology_package_status"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "package_key", name="uq_company_ontology_package_key"),
    )
    op.create_index(op.f("ix_company_ontology_packages_status"), "company_ontology_packages", ["status"], unique=False)
    op.create_index(
        op.f("ix_company_ontology_packages_tenant_id"), "company_ontology_packages", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_knowledge_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="8", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed','cancelled')",
            name="ck_company_knowledge_outbox_status",
        ),
        sa.ForeignKeyConstraint(["event_id"], ["company_knowledge_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_company_knowledge_outbox_idempotency"),
    )
    op.create_index(
        op.f("ix_company_knowledge_outbox_aggregate_id"), "company_knowledge_outbox", ["aggregate_id"], unique=False
    )
    op.create_index(
        "ix_company_knowledge_outbox_claim",
        "company_knowledge_outbox",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_company_knowledge_outbox_status"), "company_knowledge_outbox", ["status"], unique=False)
    op.create_index(
        op.f("ix_company_knowledge_outbox_tenant_id"), "company_knowledge_outbox", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_knowledge_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_contract_id", sa.UUID(), nullable=False),
        sa.Column("source_contract_version", sa.Integer(), nullable=False),
        sa.Column("source_item_id", sa.String(length=500), nullable=False),
        sa.Column("source_revision", sa.String(length=300), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("canonical_artifact_ref", sa.String(length=1000), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_acl_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("source_acl_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retention_state_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("legal_hold", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cursor_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lineage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("created_by_type", sa.String(length=30), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_knowledge_source_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('registered','ingested','blocked_source_authority','drifted','retired')",
            name="ck_company_knowledge_source_status",
        ),
        sa.ForeignKeyConstraint(["source_contract_id"], ["company_knowledge_source_contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "source_contract_id",
            "source_item_id",
            "source_revision",
            name="uq_company_knowledge_source_revision",
        ),
    )
    op.create_index(
        op.f("ix_company_knowledge_sources_content_hash"), "company_knowledge_sources", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_sources_namespace"), "company_knowledge_sources", ["namespace"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_sources_source_acl_snapshot_hash"),
        "company_knowledge_sources",
        ["source_acl_snapshot_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_sources_source_contract_id"),
        "company_knowledge_sources",
        ["source_contract_id"],
        unique=False,
    )
    op.create_index(op.f("ix_company_knowledge_sources_status"), "company_knowledge_sources", ["status"], unique=False)
    op.create_index(
        op.f("ix_company_knowledge_sources_tenant_id"), "company_knowledge_sources", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_package_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.String(length=1000), nullable=False),
        sa.Column("signature_key_ref", sa.String(length=500), nullable=False),
        sa.Column("hive_contract_version", sa.String(length=120), nullable=False),
        sa.Column("engine_capabilities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("namespaces_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dependencies_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflicts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mappings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("queries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permissions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acceptance_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("migrations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("admission_status", sa.String(length=30), nullable=False),
        sa.Column("admission_receipt_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "admission_status IN ('pending','admitted','rejected','incompatible')",
            name="ck_company_ontology_package_admission",
        ),
        sa.ForeignKeyConstraint(["package_id"], ["company_ontology_packages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "content_hash", name="uq_company_ontology_package_content_hash"),
        sa.UniqueConstraint("tenant_id", "package_id", "version", name="uq_company_ontology_package_version"),
    )
    op.create_index(
        op.f("ix_company_ontology_package_versions_admission_status"),
        "company_ontology_package_versions",
        ["admission_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_package_versions_package_id"),
        "company_ontology_package_versions",
        ["package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_package_versions_tenant_id"),
        "company_ontology_package_versions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_knowledge_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_contract_id", sa.UUID(), nullable=False),
        sa.Column("source_contract_version", sa.Integer(), nullable=False),
        sa.Column("evidence_kind", sa.String(length=40), nullable=False),
        sa.Column("source_item_id", sa.String(length=500), nullable=False),
        sa.Column("source_revision", sa.String(length=300), nullable=False),
        sa.Column("artifact_ref", sa.String(length=1000), nullable=True),
        sa.Column("schema_ref", sa.String(length=1000), nullable=True),
        sa.Column("typed_payload_ref", sa.String(length=1000), nullable=True),
        sa.Column("canonical_envelope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_acl_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("source_acl_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cursor_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence", sa.String(length=300), nullable=True),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("coverage_ledger_ref", sa.String(length=1000), nullable=False),
        sa.Column("coverage_ledger_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ingestion_receipt_ref", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "evidence_kind IN ('document','structured_record','event','living_object_revision','external_immutable_ref')",
            name="ck_company_knowledge_evidence_kind",
        ),
        sa.CheckConstraint(
            "status IN ('accepted','blocked_source_authority','quarantined','revoked')",
            name="ck_company_knowledge_evidence_status",
        ),
        sa.ForeignKeyConstraint(["source_contract_id"], ["company_knowledge_source_contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["company_knowledge_sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_company_knowledge_evidence_idempotency"),
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_content_hash"), "company_knowledge_evidence", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_evidence_kind"),
        "company_knowledge_evidence",
        ["evidence_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_source_acl_snapshot_hash"),
        "company_knowledge_evidence",
        ["source_acl_snapshot_hash"],
        unique=False,
    )
    op.create_index(
        "ix_company_knowledge_evidence_source_created",
        "company_knowledge_evidence",
        ["tenant_id", "source_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_source_id"), "company_knowledge_evidence", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_status"), "company_knowledge_evidence", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_evidence_tenant_id"), "company_knowledge_evidence", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_knowledge_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("proposal_kind", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("source_revision_ref", sa.String(length=1000), nullable=True),
        sa.Column("baseline_publication_id", sa.UUID(), nullable=True),
        sa.Column("baseline_version", sa.Integer(), nullable=True),
        sa.Column("proposed_patch_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_content_hash", sa.String(length=64), nullable=False),
        sa.Column("proposed_namespace", sa.String(length=300), nullable=False),
        sa.Column("proposed_sensitivity", sa.String(length=30), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_coverage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflict_candidates_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ontology_mapping_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("required_review_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_type", sa.String(length=30), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("accountable_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "proposal_kind IN ('knowledge','ontology','combined','personal_promotion','living_object','legacy_import')",
            name="ck_company_knowledge_proposal_kind",
        ),
        sa.CheckConstraint(
            "proposed_sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_kp_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('draft','submitted','in_review','changes_requested','approved','rejected','withdrawn','publishing','published','publish_failed','superseded','retired','restored')",
            name="ck_company_knowledge_proposal_status",
        ),
        sa.ForeignKeyConstraint(["accountable_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_document_id"], ["knowledge_documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["company_knowledge_sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_company_knowledge_proposal_idempotency"),
    )
    op.create_index(
        "ix_company_knowledge_proposal_queue",
        "company_knowledge_proposals",
        ["tenant_id", "status", "submitted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_proposals_proposed_namespace"),
        "company_knowledge_proposals",
        ["proposed_namespace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_proposals_source_id"), "company_knowledge_proposals", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_proposals_status"), "company_knowledge_proposals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_proposals_tenant_id"), "company_knowledge_proposals", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_package_installations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_capabilities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compatibility_receipt_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acceptance_receipt_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("installed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('installed','blocked','uninstalled')", name="ck_company_ontology_package_installation_status"
        ),
        sa.ForeignKeyConstraint(["installed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["package_version_id"], ["company_ontology_package_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "package_version_id", name="uq_company_ontology_package_installation"),
    )
    op.create_index(
        op.f("ix_company_ontology_package_installations_package_version_id"),
        "company_ontology_package_installations",
        ["package_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_package_installations_status"),
        "company_ontology_package_installations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_package_installations_tenant_id"),
        "company_ontology_package_installations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_knowledge_publications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("logical_resource_key", sa.String(length=500), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact_ref", sa.String(length=1000), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("review_set_hash", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_bundle_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_publication_id", sa.UUID(), nullable=True),
        sa.Column("rollback_ref", sa.String(length=1000), nullable=False),
        sa.Column("companion_release_ref", sa.String(length=500), nullable=True),
        sa.Column("published_by_user_id", sa.UUID(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_from_publication_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_knowledge_publication_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('active','superseded','retired','revoked')", name="ck_company_knowledge_publication_status"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["proposal_id"], ["company_knowledge_proposals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["published_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["restored_from_publication_id"], ["company_knowledge_publications.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_publication_id"], ["company_knowledge_publications.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "logical_resource_key", "version", name="uq_company_knowledge_publication_version"
        ),
    )
    op.create_index(
        "ix_company_knowledge_publication_active",
        "company_knowledge_publications",
        ["tenant_id", "logical_resource_key"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_company_knowledge_publication_discovery",
        "company_knowledge_publications",
        ["tenant_id", "namespace", "status", "valid_from", "valid_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_content_hash"),
        "company_knowledge_publications",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_document_id"),
        "company_knowledge_publications",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_namespace"),
        "company_knowledge_publications",
        ["namespace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_proposal_id"),
        "company_knowledge_publications",
        ["proposal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_status"), "company_knowledge_publications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_publications_tenant_id"),
        "company_knowledge_publications",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_knowledge_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_role", sa.String(length=80), nullable=False),
        sa.Column("review_round", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approve','reject','request_changes','abstain')", name="ck_company_knowledge_review_decision"
        ),
        sa.ForeignKeyConstraint(["proposal_id"], ["company_knowledge_proposals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "proposal_id", "reviewer_user_id", "review_round", name="uq_company_knowledge_review_round"
        ),
    )
    op.create_index(
        "ix_company_knowledge_review_proposal_created",
        "company_knowledge_reviews",
        ["tenant_id", "proposal_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_knowledge_reviews_proposal_id"), "company_knowledge_reviews", ["proposal_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_knowledge_reviews_tenant_id"), "company_knowledge_reviews", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_activations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("activation_version", sa.Integer(), nullable=False),
        sa.Column("configuration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dry_run_receipt_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_activation_id", sa.UUID(), nullable=True),
        sa.Column("activated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','dry_run_passed','active','superseded','retired','blocked')",
            name="ck_company_ontology_activation_status",
        ),
        sa.ForeignKeyConstraint(["activated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["company_ontology_package_installations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["supersedes_activation_id"], ["company_ontology_activations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "installation_id",
            "namespace",
            "activation_version",
            name="uq_company_ontology_activation_version",
        ),
    )
    op.create_index(
        "ix_company_ontology_activation_active",
        "company_ontology_activations",
        ["tenant_id", "namespace"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_company_ontology_activations_installation_id"),
        "company_ontology_activations",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_activations_status"), "company_ontology_activations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_activations_tenant_id"), "company_ontology_activations", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_evidence_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("subject_kind", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("bundle_key", sa.String(length=500), nullable=False),
        sa.Column("support_mode", sa.String(length=40), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("source_acl_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','held_for_authority_review','revoked')",
            name="ck_company_ontology_evidence_binding_status",
        ),
        sa.CheckConstraint(
            "support_mode IN ('joint','independent_sufficient')", name="ck_company_ontology_evidence_support_mode"
        ),
        sa.ForeignKeyConstraint(["evidence_id"], ["company_knowledge_evidence.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "subject_kind",
            "subject_id",
            "bundle_key",
            "evidence_id",
            name="uq_company_ontology_evidence_binding",
        ),
    )
    op.create_index(
        op.f("ix_company_ontology_evidence_bindings_subject_id"),
        "company_ontology_evidence_bindings",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_evidence_bindings_tenant_id"),
        "company_ontology_evidence_bindings",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_curation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("runtime_task_id", sa.UUID(), nullable=True),
        sa.Column("activation_id", sa.UUID(), nullable=False),
        sa.Column("baseline_release_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("source_contract_versions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("authority_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_operations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_prompt_receipts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate_patch_ref", sa.String(length=1000), nullable=True),
        sa.Column("candidate_patch_hash", sa.String(length=64), nullable=True),
        sa.Column("coverage_ledger_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflict_ledger_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unresolved_questions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acceptance_result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("retry_state_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint_ref", sa.String(length=1000), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("created_by_type", sa.String(length=30), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("accountable_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','checkpointed','held','quarantined','completed','failed','cancelled')",
            name="ck_company_ontology_curation_status",
        ),
        sa.ForeignKeyConstraint(["accountable_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["activation_id"], ["company_ontology_activations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["runtime_task_id"], ["runtime_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_company_ontology_curation_idempotency"),
    )
    op.create_index(
        "ix_company_ontology_curation_recovery",
        "company_ontology_curation_runs",
        ["tenant_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_curation_runs_runtime_task_id"),
        "company_ontology_curation_runs",
        ["runtime_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_curation_runs_status"), "company_ontology_curation_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_curation_runs_tenant_id"),
        "company_ontology_curation_runs",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("activation_id", sa.UUID(), nullable=False),
        sa.Column("package_version_id", sa.UUID(), nullable=False),
        sa.Column("curation_run_id", sa.UUID(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("release_hash", sa.String(length=64), nullable=False),
        sa.Column("review_set_hash", sa.String(length=64), nullable=False),
        sa.Column("source_coverage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflict_ledger_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unresolved_questions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deterministic_validation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic_review_receipts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acceptance_result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("migration_plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rollback_ref", sa.String(length=1000), nullable=False),
        sa.Column("projection_rebuild_plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_release_id", sa.UUID(), nullable=True),
        sa.Column("restored_from_release_id", sa.UUID(), nullable=True),
        sa.Column("published_by_user_id", sa.UUID(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','superseded','retired','revoked','publish_failed')",
            name="ck_company_ontology_release_status",
        ),
        sa.ForeignKeyConstraint(["activation_id"], ["company_ontology_activations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["curation_run_id"], ["company_ontology_curation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["package_version_id"], ["company_ontology_package_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["proposal_id"], ["company_knowledge_proposals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["published_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["restored_from_release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "namespace", "version", name="uq_company_ontology_release_version"),
    )
    op.create_index(
        "ix_company_ontology_release_active",
        "company_ontology_releases",
        ["tenant_id", "namespace"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_company_ontology_releases_release_hash"), "company_ontology_releases", ["release_hash"], unique=False
    )
    op.create_index(op.f("ix_company_ontology_releases_status"), "company_ontology_releases", ["status"], unique=False)
    op.create_index(
        op.f("ix_company_ontology_releases_tenant_id"), "company_ontology_releases", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_action_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("action_type_ref", sa.String(length=500), nullable=False),
        sa.Column("input_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_capability", sa.String(length=300), nullable=False),
        sa.Column("tool_workflow_mapping_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approval_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("side_effect_classification", sa.String(length=80), nullable=False),
        sa.Column("simulation_contract_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')",
            name="ck_company_ontology_action_type_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "action_type_ref", name="uq_company_ontology_action_type"),
    )
    op.create_index(
        op.f("ix_company_ontology_action_types_release_id"),
        "company_ontology_action_types",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_action_types_tenant_id"), "company_ontology_action_types", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_event_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("event_type_ref", sa.String(length=500), nullable=False),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')",
            name="ck_company_ontology_event_type_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "event_type_ref", name="uq_company_ontology_event_type"),
    )
    op.create_index(
        op.f("ix_company_ontology_event_types_release_id"), "company_ontology_event_types", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_event_types_tenant_id"), "company_ontology_event_types", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_link_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("link_type_ref", sa.String(length=500), nullable=False),
        sa.Column("from_type_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("to_type_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')",
            name="ck_company_ontology_link_type_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "link_type_ref", name="uq_company_ontology_link_type"),
    )
    op.create_index(
        op.f("ix_company_ontology_link_types_release_id"), "company_ontology_link_types", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_link_types_tenant_id"), "company_ontology_link_types", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_object_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("type_ref", sa.String(length=500), nullable=False),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')",
            name="ck_company_ontology_object_type_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "type_ref", name="uq_company_ontology_object_type"),
    )
    op.create_index(
        op.f("ix_company_ontology_object_types_release_id"),
        "company_ontology_object_types",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_object_types_tenant_id"), "company_ontology_object_types", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("stable_object_key", sa.String(length=500), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("object_type_ref", sa.String(length=500), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("properties_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_object_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_ontology_object_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','held','superseded','retired','revoked')",
            name="ck_company_ontology_object_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "stable_object_key", name="uq_company_ontology_object_key"),
    )
    op.create_index(
        "ix_company_ontology_object_type_status",
        "company_ontology_objects",
        ["tenant_id", "object_type_ref", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_objects_release_id"), "company_ontology_objects", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_objects_tenant_id"), "company_ontology_objects", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_property_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("property_ref", sa.String(length=500), nullable=False),
        sa.Column("owner_type_ref", sa.String(length=500), nullable=False),
        sa.Column("value_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cardinality_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')",
            name="ck_company_ontology_property_type_status",
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "property_ref", name="uq_company_ontology_property_type"),
    )
    op.create_index(
        op.f("ix_company_ontology_property_types_release_id"),
        "company_ontology_property_types",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_property_types_tenant_id"),
        "company_ontology_property_types",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_release_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("item_kind", sa.String(length=50), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("item_hash", sa.String(length=64), nullable=False),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "item_kind", "item_id", name="uq_company_ontology_release_item"),
    )
    op.create_index(
        op.f("ix_company_ontology_release_items_release_id"),
        "company_ontology_release_items",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_release_items_tenant_id"),
        "company_ontology_release_items",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_rule_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=300), nullable=False),
        sa.Column("rule_ref", sa.String(length=500), nullable=False),
        sa.Column("rule_kind", sa.String(length=80), nullable=False),
        sa.Column("owner_principal_ref", sa.String(length=500), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("examples_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("counterexamples_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk", sa.String(length=40), nullable=False),
        sa.Column("review_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflict_precedence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=50), nullable=False),
        sa.Column("acceptance_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "evaluation_mode IN ('deterministic_typed','llm_semantic_candidate','human_decision','external_authoritative_result')",
            name="ck_company_ontology_rule_evaluation",
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','retired','revoked')", name="ck_company_ontology_rule_status"
        ),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "release_id", "rule_ref", name="uq_company_ontology_rule_definition"),
    )
    op.create_index(
        op.f("ix_company_ontology_rule_definitions_release_id"),
        "company_ontology_rule_definitions",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_rule_definitions_tenant_id"),
        "company_ontology_rule_definitions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "company_ontology_assertions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("subject_object_id", sa.UUID(), nullable=False),
        sa.Column("predicate_ref", sa.String(length=500), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("typed_value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assertion_kind", sa.String(length=30), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_bundle_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("derived_by_rule_ref", sa.String(length=500), nullable=True),
        sa.Column("curation_run_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_assertion_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "assertion_kind IN ('sourced','derived','tenant_authored')", name="ck_company_ontology_assertion_kind"
        ),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_ontology_assertion_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','held','revoked')",
            name="ck_company_ontology_assertion_status",
        ),
        sa.ForeignKeyConstraint(["curation_run_id"], ["company_ontology_curation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_assertion_id"], ["company_ontology_assertions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_ontology_assertion_subject",
        "company_ontology_assertions",
        ["tenant_id", "subject_object_id", "predicate_ref", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_assertions_release_id"), "company_ontology_assertions", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_assertions_status"), "company_ontology_assertions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_ontology_assertions_subject_object_id"),
        "company_ontology_assertions",
        ["subject_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_assertions_tenant_id"), "company_ontology_assertions", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("stable_event_key", sa.String(length=500), nullable=False),
        sa.Column("event_type_ref", sa.String(length=500), nullable=False),
        sa.Column("subject_object_id", sa.UUID(), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sequence", sa.String(length=300), nullable=True),
        sa.Column("evidence_bundle_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("curation_run_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_ontology_event_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','held','revoked')", name="ck_company_ontology_event_status"
        ),
        sa.ForeignKeyConstraint(["curation_run_id"], ["company_ontology_curation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "stable_event_key", name="uq_company_ontology_event_key"),
    )
    op.create_index(
        op.f("ix_company_ontology_events_tenant_id"), "company_ontology_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "company_ontology_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("link_type_ref", sa.String(length=500), nullable=False),
        sa.Column("from_object_id", sa.UUID(), nullable=False),
        sa.Column("to_object_id", sa.UUID(), nullable=False),
        sa.Column("properties_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_bundle_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("curation_run_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("permission_resource_ref", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_link_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
            name="ck_company_ontology_link_sensitivity",
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','held','revoked')", name="ck_company_ontology_link_status"
        ),
        sa.ForeignKeyConstraint(["curation_run_id"], ["company_ontology_curation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["from_object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["release_id"], ["company_ontology_releases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_link_id"], ["company_ontology_links.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_ontology_link_from",
        "company_ontology_links",
        ["tenant_id", "from_object_id", "link_type_ref", "status"],
        unique=False,
    )
    op.create_index(
        "ix_company_ontology_link_to",
        "company_ontology_links",
        ["tenant_id", "to_object_id", "link_type_ref", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_company_ontology_links_tenant_id"), "company_ontology_links", ["tenant_id"], unique=False)
    op.create_table(
        "company_ontology_object_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("source_contract_id", sa.UUID(), nullable=False),
        sa.Column("source_identity_key", sa.String(length=700), nullable=False),
        sa.Column("aliases_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lineage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("curation_run_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','merged','split','held','revoked')", name="ck_company_ontology_object_identity_status"
        ),
        sa.ForeignKeyConstraint(["curation_run_id"], ["company_ontology_curation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["object_id"], ["company_ontology_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_contract_id"], ["company_knowledge_source_contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "source_contract_id", "source_identity_key", name="uq_company_ontology_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_company_ontology_object_identities_object_id"),
        "company_ontology_object_identities",
        ["object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_ontology_object_identities_tenant_id"),
        "company_ontology_object_identities",
        ["tenant_id"],
        unique=False,
    )
    op.add_column("resource_permissions", sa.Column("principal_key", sa.String(length=300), nullable=True))
    op.add_column("resource_permissions", sa.Column("resource_key", sa.String(length=500), nullable=True))
    op.add_column(
        "resource_permissions", sa.Column("effect", sa.String(length=10), server_default="allow", nullable=False)
    )
    op.add_column(
        "resource_permissions",
        sa.Column("sensitivity_ceiling", sa.String(length=30), server_default="PL1_public", nullable=False),
    )
    op.add_column(
        "resource_permissions", sa.Column("purposes", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False)
    )
    op.add_column("resource_permissions", sa.Column("source_acl_snapshot_hash", sa.String(length=64), nullable=True))
    op.add_column("resource_permissions", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("resource_permissions", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("resource_permissions", sa.Column("created_by_user_id", sa.UUID(), nullable=True))
    op.add_column("resource_permissions", sa.Column("revoked_by_user_id", sa.UUID(), nullable=True))
    op.execute("ALTER TABLE resource_permissions ALTER COLUMN principal_id DROP NOT NULL")
    op.alter_column(
        "resource_permissions",
        "resource_type",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=80),
        existing_nullable=False,
    )
    op.execute("ALTER TABLE resource_permissions ALTER COLUMN resource_id DROP NOT NULL")
    op.create_index(op.f("ix_resource_permissions_expires_at"), "resource_permissions", ["expires_at"], unique=False)
    op.create_index(
        "ix_resource_permissions_principal_key_resource_key",
        "resource_permissions",
        ["tenant_id", "principal_type", "principal_key", "resource_type", "resource_key"],
        unique=False,
    )
    op.create_index(op.f("ix_resource_permissions_revoked_at"), "resource_permissions", ["revoked_at"], unique=False)
    op.create_foreign_key(
        "fk_resource_permissions_revoked_by_user",
        "resource_permissions",
        "users",
        ["revoked_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_resource_permissions_created_by_user",
        "resource_permissions",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ck_resource_permissions_principal_ref",
        "resource_permissions",
        "principal_id IS NOT NULL OR principal_key IS NOT NULL",
    )
    op.create_check_constraint(
        "ck_resource_permissions_resource_ref",
        "resource_permissions",
        "resource_id IS NOT NULL OR resource_key IS NOT NULL",
    )
    op.create_check_constraint(
        "ck_resource_permissions_effect",
        "resource_permissions",
        "effect IN ('allow','deny')",
    )
    op.create_check_constraint(
        "ck_resource_permissions_sensitivity_ceiling",
        "resource_permissions",
        "sensitivity_ceiling IN ('PL1_public','PL2_pii','PL3_sensitive','PL4_credential')",
    )
    op.create_check_constraint(
        "ck_resource_permissions_revoke_actor",
        "resource_permissions",
        "revoked_by_user_id IS NULL OR revoked_at IS NOT NULL",
    )
    op.create_foreign_key(
        "fk_company_knowledge_proposal_baseline_publication",
        "company_knowledge_proposals",
        "company_knowledge_publications",
        ["baseline_publication_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_company_ontology_curation_baseline_release",
        "company_ontology_curation_runs",
        "company_ontology_releases",
        ["baseline_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    for table in TENANT_TABLES:
        _enable_strict_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM resource_permissions
            WHERE principal_id IS NULL
               OR resource_id IS NULL
               OR effect <> 'allow'
               OR sensitivity_ceiling <> 'PL1_public'
               OR cardinality(purposes) > 0
               OR source_acl_snapshot_hash IS NOT NULL
               OR expires_at IS NOT NULL
               OR revoked_at IS NOT NULL
          ) THEN
            RAISE EXCEPTION
              'secure downgrade blocked: ResourcePermission rows use Company Knowledge authority semantics';
          END IF;
        END
        $$;
        """
    )
    op.drop_constraint(
        "fk_company_ontology_curation_baseline_release",
        "company_ontology_curation_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_company_knowledge_proposal_baseline_publication",
        "company_knowledge_proposals",
        type_="foreignkey",
    )
    op.drop_constraint("ck_resource_permissions_revoke_actor", "resource_permissions", type_="check")
    op.drop_constraint("ck_resource_permissions_sensitivity_ceiling", "resource_permissions", type_="check")
    op.drop_constraint("ck_resource_permissions_effect", "resource_permissions", type_="check")
    op.drop_constraint("ck_resource_permissions_resource_ref", "resource_permissions", type_="check")
    op.drop_constraint("ck_resource_permissions_principal_ref", "resource_permissions", type_="check")
    op.drop_constraint("fk_resource_permissions_created_by_user", "resource_permissions", type_="foreignkey")
    op.drop_constraint("fk_resource_permissions_revoked_by_user", "resource_permissions", type_="foreignkey")
    op.drop_index(op.f("ix_resource_permissions_revoked_at"), table_name="resource_permissions")
    op.drop_index("ix_resource_permissions_principal_key_resource_key", table_name="resource_permissions")
    op.drop_index(op.f("ix_resource_permissions_expires_at"), table_name="resource_permissions")
    op.alter_column("resource_permissions", "resource_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "resource_permissions",
        "resource_type",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column("resource_permissions", "principal_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("resource_permissions", "revoked_by_user_id")
    op.drop_column("resource_permissions", "created_by_user_id")
    op.drop_column("resource_permissions", "revoked_at")
    op.drop_column("resource_permissions", "expires_at")
    op.drop_column("resource_permissions", "source_acl_snapshot_hash")
    op.drop_column("resource_permissions", "purposes")
    op.drop_column("resource_permissions", "sensitivity_ceiling")
    op.drop_column("resource_permissions", "effect")
    op.drop_column("resource_permissions", "resource_key")
    op.drop_column("resource_permissions", "principal_key")
    op.drop_index(
        op.f("ix_company_ontology_object_identities_tenant_id"), table_name="company_ontology_object_identities"
    )
    op.drop_index(
        op.f("ix_company_ontology_object_identities_object_id"), table_name="company_ontology_object_identities"
    )
    op.drop_table("company_ontology_object_identities")
    op.drop_index(op.f("ix_company_ontology_links_tenant_id"), table_name="company_ontology_links")
    op.drop_index("ix_company_ontology_link_to", table_name="company_ontology_links")
    op.drop_index("ix_company_ontology_link_from", table_name="company_ontology_links")
    op.drop_table("company_ontology_links")
    op.drop_index(op.f("ix_company_ontology_events_tenant_id"), table_name="company_ontology_events")
    op.drop_table("company_ontology_events")
    op.drop_index(op.f("ix_company_ontology_assertions_tenant_id"), table_name="company_ontology_assertions")
    op.drop_index(op.f("ix_company_ontology_assertions_subject_object_id"), table_name="company_ontology_assertions")
    op.drop_index(op.f("ix_company_ontology_assertions_status"), table_name="company_ontology_assertions")
    op.drop_index(op.f("ix_company_ontology_assertions_release_id"), table_name="company_ontology_assertions")
    op.drop_index("ix_company_ontology_assertion_subject", table_name="company_ontology_assertions")
    op.drop_table("company_ontology_assertions")
    op.drop_index(
        op.f("ix_company_ontology_rule_definitions_tenant_id"), table_name="company_ontology_rule_definitions"
    )
    op.drop_index(
        op.f("ix_company_ontology_rule_definitions_release_id"), table_name="company_ontology_rule_definitions"
    )
    op.drop_table("company_ontology_rule_definitions")
    op.drop_index(op.f("ix_company_ontology_release_items_tenant_id"), table_name="company_ontology_release_items")
    op.drop_index(op.f("ix_company_ontology_release_items_release_id"), table_name="company_ontology_release_items")
    op.drop_table("company_ontology_release_items")
    op.drop_index(op.f("ix_company_ontology_property_types_tenant_id"), table_name="company_ontology_property_types")
    op.drop_index(op.f("ix_company_ontology_property_types_release_id"), table_name="company_ontology_property_types")
    op.drop_table("company_ontology_property_types")
    op.drop_index(op.f("ix_company_ontology_objects_tenant_id"), table_name="company_ontology_objects")
    op.drop_index(op.f("ix_company_ontology_objects_release_id"), table_name="company_ontology_objects")
    op.drop_index("ix_company_ontology_object_type_status", table_name="company_ontology_objects")
    op.drop_table("company_ontology_objects")
    op.drop_index(op.f("ix_company_ontology_object_types_tenant_id"), table_name="company_ontology_object_types")
    op.drop_index(op.f("ix_company_ontology_object_types_release_id"), table_name="company_ontology_object_types")
    op.drop_table("company_ontology_object_types")
    op.drop_index(op.f("ix_company_ontology_link_types_tenant_id"), table_name="company_ontology_link_types")
    op.drop_index(op.f("ix_company_ontology_link_types_release_id"), table_name="company_ontology_link_types")
    op.drop_table("company_ontology_link_types")
    op.drop_index(op.f("ix_company_ontology_event_types_tenant_id"), table_name="company_ontology_event_types")
    op.drop_index(op.f("ix_company_ontology_event_types_release_id"), table_name="company_ontology_event_types")
    op.drop_table("company_ontology_event_types")
    op.drop_index(op.f("ix_company_ontology_action_types_tenant_id"), table_name="company_ontology_action_types")
    op.drop_index(op.f("ix_company_ontology_action_types_release_id"), table_name="company_ontology_action_types")
    op.drop_table("company_ontology_action_types")
    op.drop_index(op.f("ix_company_ontology_releases_tenant_id"), table_name="company_ontology_releases")
    op.drop_index(op.f("ix_company_ontology_releases_status"), table_name="company_ontology_releases")
    op.drop_index(op.f("ix_company_ontology_releases_release_hash"), table_name="company_ontology_releases")
    op.drop_index(
        "ix_company_ontology_release_active",
        table_name="company_ontology_releases",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("company_ontology_releases")
    op.drop_index(op.f("ix_company_ontology_curation_runs_tenant_id"), table_name="company_ontology_curation_runs")
    op.drop_index(op.f("ix_company_ontology_curation_runs_status"), table_name="company_ontology_curation_runs")
    op.drop_index(
        op.f("ix_company_ontology_curation_runs_runtime_task_id"), table_name="company_ontology_curation_runs"
    )
    op.drop_index("ix_company_ontology_curation_recovery", table_name="company_ontology_curation_runs")
    op.drop_table("company_ontology_curation_runs")
    op.drop_index(
        op.f("ix_company_ontology_evidence_bindings_tenant_id"), table_name="company_ontology_evidence_bindings"
    )
    op.drop_index(
        op.f("ix_company_ontology_evidence_bindings_subject_id"), table_name="company_ontology_evidence_bindings"
    )
    op.drop_table("company_ontology_evidence_bindings")
    op.drop_index(op.f("ix_company_ontology_activations_tenant_id"), table_name="company_ontology_activations")
    op.drop_index(op.f("ix_company_ontology_activations_status"), table_name="company_ontology_activations")
    op.drop_index(op.f("ix_company_ontology_activations_installation_id"), table_name="company_ontology_activations")
    op.drop_index(
        "ix_company_ontology_activation_active",
        table_name="company_ontology_activations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("company_ontology_activations")
    op.drop_index(op.f("ix_company_knowledge_reviews_tenant_id"), table_name="company_knowledge_reviews")
    op.drop_index(op.f("ix_company_knowledge_reviews_proposal_id"), table_name="company_knowledge_reviews")
    op.drop_index("ix_company_knowledge_review_proposal_created", table_name="company_knowledge_reviews")
    op.drop_table("company_knowledge_reviews")
    op.drop_index(op.f("ix_company_knowledge_publications_tenant_id"), table_name="company_knowledge_publications")
    op.drop_index(op.f("ix_company_knowledge_publications_status"), table_name="company_knowledge_publications")
    op.drop_index(op.f("ix_company_knowledge_publications_proposal_id"), table_name="company_knowledge_publications")
    op.drop_index(op.f("ix_company_knowledge_publications_namespace"), table_name="company_knowledge_publications")
    op.drop_index(op.f("ix_company_knowledge_publications_document_id"), table_name="company_knowledge_publications")
    op.drop_index(op.f("ix_company_knowledge_publications_content_hash"), table_name="company_knowledge_publications")
    op.drop_index("ix_company_knowledge_publication_discovery", table_name="company_knowledge_publications")
    op.drop_index(
        "ix_company_knowledge_publication_active",
        table_name="company_knowledge_publications",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("company_knowledge_publications")
    op.drop_index(
        op.f("ix_company_ontology_package_installations_tenant_id"), table_name="company_ontology_package_installations"
    )
    op.drop_index(
        op.f("ix_company_ontology_package_installations_status"), table_name="company_ontology_package_installations"
    )
    op.drop_index(
        op.f("ix_company_ontology_package_installations_package_version_id"),
        table_name="company_ontology_package_installations",
    )
    op.drop_table("company_ontology_package_installations")
    op.drop_index(op.f("ix_company_knowledge_proposals_tenant_id"), table_name="company_knowledge_proposals")
    op.drop_index(op.f("ix_company_knowledge_proposals_status"), table_name="company_knowledge_proposals")
    op.drop_index(op.f("ix_company_knowledge_proposals_source_id"), table_name="company_knowledge_proposals")
    op.drop_index(op.f("ix_company_knowledge_proposals_proposed_namespace"), table_name="company_knowledge_proposals")
    op.drop_index("ix_company_knowledge_proposal_queue", table_name="company_knowledge_proposals")
    op.drop_table("company_knowledge_proposals")
    op.drop_index(op.f("ix_company_knowledge_evidence_tenant_id"), table_name="company_knowledge_evidence")
    op.drop_index(op.f("ix_company_knowledge_evidence_status"), table_name="company_knowledge_evidence")
    op.drop_index(op.f("ix_company_knowledge_evidence_source_id"), table_name="company_knowledge_evidence")
    op.drop_index("ix_company_knowledge_evidence_source_created", table_name="company_knowledge_evidence")
    op.drop_index(
        op.f("ix_company_knowledge_evidence_source_acl_snapshot_hash"), table_name="company_knowledge_evidence"
    )
    op.drop_index(op.f("ix_company_knowledge_evidence_evidence_kind"), table_name="company_knowledge_evidence")
    op.drop_index(op.f("ix_company_knowledge_evidence_content_hash"), table_name="company_knowledge_evidence")
    op.drop_table("company_knowledge_evidence")
    op.drop_index(
        op.f("ix_company_ontology_package_versions_tenant_id"), table_name="company_ontology_package_versions"
    )
    op.drop_index(
        op.f("ix_company_ontology_package_versions_package_id"), table_name="company_ontology_package_versions"
    )
    op.drop_index(
        op.f("ix_company_ontology_package_versions_admission_status"), table_name="company_ontology_package_versions"
    )
    op.drop_table("company_ontology_package_versions")
    op.drop_index(op.f("ix_company_knowledge_sources_tenant_id"), table_name="company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_sources_status"), table_name="company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_sources_source_contract_id"), table_name="company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_sources_source_acl_snapshot_hash"), table_name="company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_sources_namespace"), table_name="company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_sources_content_hash"), table_name="company_knowledge_sources")
    op.drop_table("company_knowledge_sources")
    op.drop_index(op.f("ix_company_knowledge_outbox_tenant_id"), table_name="company_knowledge_outbox")
    op.drop_index(op.f("ix_company_knowledge_outbox_status"), table_name="company_knowledge_outbox")
    op.drop_index("ix_company_knowledge_outbox_claim", table_name="company_knowledge_outbox")
    op.drop_index(op.f("ix_company_knowledge_outbox_aggregate_id"), table_name="company_knowledge_outbox")
    op.drop_table("company_knowledge_outbox")
    op.drop_index(op.f("ix_company_ontology_packages_tenant_id"), table_name="company_ontology_packages")
    op.drop_index(op.f("ix_company_ontology_packages_status"), table_name="company_ontology_packages")
    op.drop_table("company_ontology_packages")
    op.drop_index(
        op.f("ix_company_knowledge_source_contracts_tenant_id"), table_name="company_knowledge_source_contracts"
    )
    op.drop_index(op.f("ix_company_knowledge_source_contracts_status"), table_name="company_knowledge_source_contracts")
    op.drop_index(
        op.f("ix_company_knowledge_source_contracts_source_kind"), table_name="company_knowledge_source_contracts"
    )
    op.drop_index(
        op.f("ix_company_knowledge_source_contracts_contract_hash"), table_name="company_knowledge_source_contracts"
    )
    op.drop_index(
        "ix_company_knowledge_source_contract_active",
        table_name="company_knowledge_source_contracts",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("company_knowledge_source_contracts")
    op.drop_index(op.f("ix_company_knowledge_events_tenant_id"), table_name="company_knowledge_events")
    op.drop_index(op.f("ix_company_knowledge_events_event_type"), table_name="company_knowledge_events")
    op.drop_index("ix_company_knowledge_event_trace", table_name="company_knowledge_events")
    op.drop_index("ix_company_knowledge_event_stream", table_name="company_knowledge_events")
    op.drop_table("company_knowledge_events")
    # ### end Alembic commands ###
