"""Immutable generated Session V2 SQL snapshot owned by revision 0716.

Do not edit this snapshot when live contract generation changes. Add a new
migration-owned snapshot and revision instead. Fresh bootstrap intentionally
continues to consume the live app.services.session_event_contract source.
"""

from __future__ import annotations

SESSION_V2_AUTHORITY_TABLES = (
    "session_event_cursors",
    "session_event_outbox",
    "session_commands",
    "session_turn_inputs",
    "session_input_admissions",
    "session_carry_forwards",
    "session_control_inputs",
    "session_turn_replacements",
    "session_tool_invocations",
    "session_model_results",
    "session_round_obligations",
    "session_next_round_plans",
    "session_run_outcomes",
    "session_feedback_aggregates",
)

SESSION_V2_TRIGGER_FUNCTION_SIGNATURES = (
    "public.enforce_session_event_v2_contract()",
    "public.enforce_session_writer_epoch()",
    "public.enforce_session_v2_tenant_binding()",
)

_SESSION_EVENT_CONTRACT_FUNCTION_SQL = (
    "\n"
    "        CREATE OR REPLACE FUNCTION public.enforce_session_event_v2_contract()\n"
    "        RETURNS trigger\n"
    "        LANGUAGE plpgsql\n"
    "        SECURITY DEFINER\n"
    "        SET search_path = pg_catalog\n"
    "        AS $$\n"
    "        DECLARE\n"
    "          event_matrix jsonb := "
    '\'{"a2a_delegation":{"lifecycles":["cancelled","completed","denied","failed","progress","queued","snapshot","started","unavailable","waiting"],"scopes":["round","run"]},"a2a_receipt":{"lifecycles":["cancelled","completed","denied","failed","progress","queued","snapshot","started","unavailable","waiting"],"scopes":["round","run"]},"approval":{"lifecycles":["cancelled","completed","created","denied","expired","waiting"],"scopes":["round","run"]},"artifact":{"lifecycles":["created","delivered","failed","updated"],"scopes":["round","run"]},"assistant_commentary":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"assistant_final":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"assistant_plan":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"assistant_reasoning_private":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"assistant_reasoning_summary":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"assistant_text":{"lifecycles":["cancelled","completed","delta","failed","snapshot","started"],"scopes":["round"]},"code_execution":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"context_compaction":{"lifecycles":["completed","failed","needs_reconciliation","progress","reconciled","started"],"scopes":["round","run"]},"context_source":{"lifecycles":["completed","denied","failed","started","unavailable"],"scopes":["round"]},"control_input":{"lifecycles":["accepted","applied","failed","needs_reconciliation","reconciled","rejected","started"],"scopes":["run"]},"evaluation_feedback_mutation":{"lifecycles":["recorded","updated","withdrawn"],"scopes":["session"]},"file_change":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"file_preview":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"file_read":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"hook":{"lifecycles":["blocked","cancelled","completed","denied","failed","prevented","started","waiting"],"scopes":["round","run","session"]},"human_input":{"lifecycles":["accepted","applied","bound","cancelled","needs_reconciliation","queued","reconciled","rejected","revised","rolled_over"],"scopes":["session"]},"image_view":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"input_admission":{"lifecycles":["admitted","cancelled","needs_reconciliation","prepared","reconciled","rejected","sealed","started"],"scopes":["session"]},"mcp_call":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"memory_commit":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"memory_load":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"memory_search":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"memory_write_proposal":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"recovery_action":{"lifecycles":["completed","failed","reconciled","requested","started"],"scopes":["run","session","turn"]},"result_commit":{"lifecycles":["failed","needs_reconciliation","prepared","reconciled","round_committed","sealed","streaming"],"scopes":["round"]},"run":{"lifecycles":["cancelled","cancelling","completed","failed","needs_reconciliation","queued","reconciled","running","starting","waiting"],"scopes":["run"]},"run_outcome":{"lifecycles":["failed","needs_reconciliation","prepared","reconciled","sealed","terminal_committed"],"scopes":["run"]},"runtime_failure":{"lifecycles":["recorded"],"scopes":["round","run","session","turn"]},"session":{"lifecycles":["created","forked","resumed"],"scopes":["session"]},"skill_load":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"skill_search":{"lifecycles":["cancelled","completed","denied","failed","progress","started","unavailable"],"scopes":["round"]},"subagent":{"lifecycles":["cancelled","completed","denied","failed","progress","queued","snapshot","started","unavailable","waiting"],"scopes":["round","run"]},"tool_call":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"tool_permission":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"tool_result":{"lifecycles":["completed"],"scopes":["round"]},"tool_search":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"turn":{"lifecycles":["accepted","cancelled","completed","failed","needs_reconciliation","queued","reconciled","started","waiting"],"scopes":["turn"]},"turn_replacement":{"lifecycles":["admitted","cancelling","completed","failed","fenced","needs_reconciliation","queued","reconciled","requested"],"scopes":["session"]},"user_question":{"lifecycles":["cancelled","completed","created","denied","expired","waiting"],"scopes":["round","run"]},"web_search":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","unavailable","waiting"],"scopes":["round"]},"workflow_gate":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","waiting"],"scopes":["round","run"]},"workflow_run":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","waiting"],"scopes":["round","run"]},"workflow_step":{"lifecycles":["cancelled","completed","denied","failed","needs_reconciliation","progress","queued","reconciled","started","waiting"],"scopes":["round","run"]}}\'::jsonb;\n'
    "          hook_matrix jsonb := "
    '\'{"PostCompact":{"lifecycles":["cancelled","completed","failed","started"],"scopes":["run"],"sources":["auto","manual","reactive"]},"PreCompact":{"lifecycles":["cancelled","completed","failed","started"],"scopes":["run"],"sources":["auto","manual","reactive"]},"PreToolUse":{"lifecycles":["blocked","cancelled","completed","denied","failed","prevented","started","waiting"],"scopes":["round"],"sources":[]},"SessionStart":{"lifecycles":["completed","failed","started"],"scopes":["session"],"sources":["clear","compact","resume","startup"]},"Stop":{"lifecycles":["blocked","cancelled","completed","failed","prevented","started"],"scopes":["run"],"sources":[]},"SubagentStop":{"lifecycles":["blocked","cancelled","completed","failed","prevented","started"],"scopes":["run"],"sources":[]},"UserPromptSubmit":{"lifecycles":["blocked","cancelled","completed","failed","prevented","started"],"scopes":["session"],"sources":[]}}\'::jsonb;\n'
    "          rule jsonb;\n"
    "          hook_rule jsonb;\n"
    "          level text;\n"
    "          boundary text;\n"
    "          source_value text;\n"
    "          allowed_scope_keys text[];\n"
    "          bound_tenant_id uuid;\n"
    "          bound_agent_id uuid;\n"
    "          epoch public.session_writer_epochs%ROWTYPE;\n"
    "          run_generation integer;\n"
    "        BEGIN\n"
    "          SELECT tenant_id,agent_id INTO bound_tenant_id,bound_agent_id\n"
    "          FROM public.chat_sessions WHERE id=NEW.session_id;\n"
    "          IF NOT FOUND OR NEW.tenant_id IS DISTINCT FROM bound_tenant_id\n"
    "             OR NEW.agent_id IS DISTINCT FROM bound_agent_id THEN\n"
    "            RAISE EXCEPTION 'session_event_authority_binding_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          SELECT * INTO epoch FROM public.session_writer_epochs WHERE id='global';\n"
    "          IF epoch.id IS NOT NULL AND epoch.enforcement_mode='enforce' THEN\n"
    "            IF NEW.schema_version <> 2 THEN\n"
    "              IF epoch.state <> 'v1_draining' OR NEW.run_id IS NULL THEN\n"
    "                RAISE EXCEPTION 'writer_epoch_rejected legacy transcript mutation' USING "
    "ERRCODE='23514';\n"
    "              END IF;\n"
    "              SELECT writer_generation INTO run_generation FROM public.runtime_tasks WHERE "
    "id=NEW.run_id;\n"
    "              IF NOT FOUND OR run_generation <> 1\n"
    "                 OR NOT epoch.allowed_existing_generations_json @> "
    "to_jsonb(ARRAY[run_generation]) THEN\n"
    "                RAISE EXCEPTION 'writer_epoch_rejected legacy run generation' USING "
    "ERRCODE='23514';\n"
    "              END IF;\n"
    "            ELSIF NEW.run_id IS NOT NULL THEN\n"
    "              SELECT writer_generation INTO run_generation FROM public.runtime_tasks WHERE "
    "id=NEW.run_id;\n"
    "              IF NOT FOUND OR run_generation <> 2\n"
    "                 OR NOT epoch.allowed_existing_generations_json @> "
    "to_jsonb(ARRAY[run_generation]) THEN\n"
    "                RAISE EXCEPTION 'writer_epoch_rejected V2 run generation' USING "
    "ERRCODE='23514';\n"
    "              END IF;\n"
    "            END IF;\n"
    "          END IF;\n"
    "          IF NEW.schema_version <> 2 AND NEW.run_id IS NOT NULL AND (\n"
    "            epoch.id IS NULL OR NOT EXISTS (\n"
    "              SELECT 1 FROM public.runtime_tasks AS legacy_run\n"
    "              WHERE legacy_run.id=NEW.run_id\n"
    "                AND legacy_run.tenant_id=NEW.tenant_id\n"
    "                AND legacy_run.parent_session_id=NEW.session_id::text\n"
    "                AND legacy_run.parent_agent_id=NEW.agent_id\n"
    "                AND epoch.allowed_existing_generations_json\n"
    "                    @> to_jsonb(ARRAY[legacy_run.writer_generation])\n"
    "            )\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'writer_epoch_rejected legacy run authority'\n"
    "              USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.schema_version <> 2 THEN RETURN NEW; END IF;\n"
    "          IF NEW.item_id IS NULL OR NEW.item_kind IS NULL OR NEW.lifecycle IS NULL\n"
    "             OR NEW.payload_schema IS NULL OR NEW.scope_json IS NULL\n"
    "             OR jsonb_typeof(NEW.scope_json) <> 'object' THEN\n"
    "            RAISE EXCEPTION 'incomplete SessionEventV2 envelope' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.event_type <> NEW.item_kind || '.' || NEW.lifecycle\n"
    "             OR NEW.payload_schema <> 'hive.session.payload.' || NEW.item_kind || '.' || "
    "NEW.lifecycle || '.v2' THEN\n"
    "            RAISE EXCEPTION 'SessionEventV2 kind/schema mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          rule := event_matrix->NEW.item_kind;\n"
    "          level := NEW.scope_json->>'level';\n"
    "          IF rule IS NULL OR NOT (rule->'lifecycles' ? NEW.lifecycle)\n"
    "             OR NOT (rule->'scopes' ? level) THEN\n"
    "            RAISE EXCEPTION 'illegal SessionEventV2 kind/lifecycle/scope tuple' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          allowed_scope_keys := CASE level\n"
    "            WHEN 'session' THEN ARRAY['level','session_id','thread_id']\n"
    "            WHEN 'turn' THEN ARRAY['level','session_id','thread_id','turn_id']\n"
    "            WHEN 'run' THEN ARRAY['level','session_id','thread_id','turn_id','run_id']\n"
    "            WHEN 'round' THEN "
    "ARRAY['level','session_id','thread_id','turn_id','run_id','round_id']\n"
    "            ELSE ARRAY[]::text[] END;\n"
    "          IF EXISTS (\n"
    "            SELECT 1 FROM jsonb_object_keys(NEW.scope_json) AS scope_key\n"
    "            WHERE NOT (scope_key = ANY(allowed_scope_keys))\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'SessionEventV2 scope contains forbidden fields' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NULLIF(NEW.scope_json->>'session_id','') IS NULL\n"
    "             OR NULLIF(NEW.scope_json->>'thread_id','') IS NULL\n"
    "             OR NEW.scope_json->>'session_id' <> NEW.scope_json->>'thread_id'\n"
    "             OR (NEW.scope_json->>'session_id')::uuid <> NEW.session_id THEN\n"
    "            RAISE EXCEPTION 'invalid SessionEventV2 session scope' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF level IN ('turn','run','round') AND NULLIF(NEW.scope_json->>'turn_id','') IS NULL "
    "THEN\n"
    "            RAISE EXCEPTION 'turn_id required by SessionEventV2 scope' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF level IN ('run','round') AND NULLIF(NEW.scope_json->>'run_id','') IS NULL THEN\n"
    "            RAISE EXCEPTION 'run_id required by SessionEventV2 scope' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF level='round' AND NULLIF(NEW.scope_json->>'round_id','') IS NULL THEN\n"
    "            RAISE EXCEPTION 'round_id required by SessionEventV2 scope' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF (level IN ('session','turn') AND NEW.run_id IS NOT NULL)\n"
    "             OR (level IN ('run','round') AND (\n"
    "                  NEW.run_id IS NULL\n"
    "                  OR NEW.run_id::text <> NEW.scope_json->>'run_id'\n"
    "             )) THEN\n"
    "            RAISE EXCEPTION 'session_event_run_scope_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.run_id IS NOT NULL AND NOT EXISTS (\n"
    "            SELECT 1 FROM public.runtime_tasks AS run\n"
    "            WHERE run.id=NEW.run_id\n"
    "              AND run.tenant_id=NEW.tenant_id\n"
    "              AND run.parent_session_id=NEW.session_id::text\n"
    "              AND run.parent_agent_id=NEW.agent_id\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_event_run_authority_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.command_id IS NOT NULL AND NOT EXISTS (\n"
    "            SELECT 1 FROM public.session_commands AS command\n"
    "            WHERE command.id=NEW.command_id\n"
    "              AND command.tenant_id=NEW.tenant_id\n"
    "              AND command.session_id=NEW.session_id\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_event_command_authority_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.input_id IS NOT NULL AND NOT EXISTS (\n"
    "            SELECT 1 FROM public.session_turn_inputs AS input\n"
    "            WHERE input.id=NEW.input_id\n"
    "              AND input.tenant_id=NEW.tenant_id\n"
    "              AND input.session_id=NEW.session_id\n"
    "              AND (NEW.command_id IS NULL OR input.command_id=NEW.command_id)\n"
    "              AND (input.target_run_id IS NULL OR NEW.run_id IS NULL OR "
    "input.target_run_id=NEW.run_id)\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_event_input_authority_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.result_id IS NOT NULL AND NOT EXISTS (\n"
    "            SELECT 1 FROM public.session_model_results AS result\n"
    "            WHERE result.id=NEW.result_id\n"
    "              AND result.tenant_id=NEW.tenant_id\n"
    "              AND result.session_id=NEW.session_id\n"
    "              AND result.run_id=NEW.run_id\n"
    "              AND result.turn_id=NEW.scope_json->>'turn_id'\n"
    "              AND result.round_id=NEW.scope_json->>'round_id'\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_event_result_authority_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.invocation_id IS NOT NULL AND NOT EXISTS (\n"
    "            SELECT 1 FROM public.session_tool_invocations AS invocation\n"
    "            WHERE invocation.id=NEW.invocation_id\n"
    "              AND invocation.tenant_id=NEW.tenant_id\n"
    "              AND invocation.session_id=NEW.session_id\n"
    "              AND invocation.run_id=NEW.run_id\n"
    "              AND invocation.round_id=NEW.scope_json->>'round_id'\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_event_invocation_authority_mismatch' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF jsonb_typeof(COALESCE(NEW.metadata_json,'{}'::jsonb)->'v2_payload') IS DISTINCT "
    "FROM 'object'\n"
    "             OR jsonb_typeof(COALESCE(NEW.metadata_json,'{}'::jsonb)->'actor') IS DISTINCT FROM "
    "'object'\n"
    "             OR jsonb_typeof(COALESCE(NEW.metadata_json,'{}'::jsonb)->'visibility') IS DISTINCT "
    "FROM 'object' THEN\n"
    "            RAISE EXCEPTION 'incomplete SessionEventV2 payload authority' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.item_kind='assistant_text'\n"
    "             AND COALESCE(NEW.metadata_json->'v2_payload'->>'phase','unknown') <> 'unknown' "
    "THEN\n"
    "            RAISE EXCEPTION 'assistant_text phase must be unknown' USING ERRCODE='23514';\n"
    "          ELSIF NEW.item_kind='assistant_commentary'\n"
    "             AND COALESCE(NEW.metadata_json->'v2_payload'->>'phase','commentary') <> "
    "'commentary' THEN\n"
    "            RAISE EXCEPTION 'assistant_commentary phase must be commentary' USING "
    "ERRCODE='23514';\n"
    "          ELSIF NEW.item_kind='assistant_reasoning_summary'\n"
    "             AND COALESCE(NEW.metadata_json->'v2_payload'->>'phase','reasoning_summary') <> "
    "'reasoning_summary' THEN\n"
    "            RAISE EXCEPTION 'assistant_reasoning_summary phase must be reasoning_summary' USING "
    "ERRCODE='23514';\n"
    "          ELSIF NEW.item_kind='assistant_reasoning_private'\n"
    "             AND COALESCE(NEW.metadata_json->'v2_payload'->>'phase','reasoning_private') <> "
    "'reasoning_private' THEN\n"
    "            RAISE EXCEPTION 'assistant_reasoning_private phase must be reasoning_private' USING "
    "ERRCODE='23514';\n"
    "          ELSIF NEW.item_kind='assistant_final'\n"
    "             AND COALESCE(NEW.metadata_json->'v2_payload'->>'phase','final') <> 'final' THEN\n"
    "            RAISE EXCEPTION 'assistant_final phase must be final' USING ERRCODE='23514';\n"
    "          ELSIF NEW.item_kind NOT IN "
    "('assistant_text','assistant_commentary','assistant_reasoning_summary',"
    "'assistant_reasoning_private','assistant_final')\n"
    "             AND NEW.metadata_json->'v2_payload' ? 'phase' THEN\n"
    "            RAISE EXCEPTION 'assistant phase is illegal for this item kind' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NEW.item_kind='hook' THEN\n"
    "            boundary := NEW.metadata_json->'v2_payload'->>'boundary';\n"
    "            source_value := COALESCE(NEW.metadata_json->'v2_payload'->>'source','');\n"
    "            hook_rule := hook_matrix->boundary;\n"
    "            IF hook_rule IS NULL OR NOT (hook_rule->'lifecycles' ? NEW.lifecycle)\n"
    "               OR NOT (hook_rule->'scopes' ? level)\n"
    "               OR (jsonb_array_length(hook_rule->'sources') > 0\n"
    "                   AND NOT (hook_rule->'sources' ? source_value))\n"
    "               OR (jsonb_array_length(hook_rule->'sources') = 0\n"
    "                   AND NEW.metadata_json->'v2_payload' ? 'source') THEN\n"
    "              RAISE EXCEPTION 'illegal SessionEventV2 hook boundary tuple' USING "
    "ERRCODE='23514';\n"
    "            END IF;\n"
    "          END IF;\n"
    "          RETURN NEW;\n"
    "        END;\n"
    "        $$\n"
    "    "
)

_SESSION_WRITER_EPOCH_FUNCTION_SQL = (
    "\n"
    "        CREATE OR REPLACE FUNCTION public.enforce_session_writer_epoch()\n"
    "        RETURNS trigger\n"
    "        LANGUAGE plpgsql\n"
    "        SECURITY DEFINER\n"
    "        SET search_path = pg_catalog\n"
    "        AS $$\n"
    "        DECLARE epoch public.session_writer_epochs%ROWTYPE;\n"
    "        BEGIN\n"
    "          SELECT * INTO epoch FROM public.session_writer_epochs WHERE id='global';\n"
    "          IF NOT FOUND OR epoch.enforcement_mode='observe' THEN RETURN NEW; END IF;\n"
    "          IF TG_OP='INSERT' THEN\n"
    "            IF NEW.writer_generation <> epoch.new_run_generation\n"
    "               OR NOT epoch.allowed_existing_generations_json @> "
    "to_jsonb(ARRAY[NEW.writer_generation]) THEN\n"
    "              RAISE EXCEPTION 'writer_epoch_rejected new run generation' USING ERRCODE='23514';\n"
    "            END IF;\n"
    "            RETURN NEW;\n"
    "          END IF;\n"
    "          IF NEW.writer_generation <> OLD.writer_generation THEN\n"
    "            RAISE EXCEPTION 'writer_generation is immutable' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF NOT epoch.allowed_existing_generations_json @> "
    "to_jsonb(ARRAY[OLD.writer_generation]) THEN\n"
    "            RAISE EXCEPTION 'writer_epoch_rejected late runtime mutation' USING "
    "ERRCODE='23514';\n"
    "          END IF;\n"
    "          RETURN NEW;\n"
    "        END;\n"
    "        $$\n"
    "    "
)

_SESSION_TENANT_BINDING_FUNCTION_SQL = (
    "\n"
    "        CREATE OR REPLACE FUNCTION public.enforce_session_v2_tenant_binding()\n"
    "        RETURNS trigger\n"
    "        LANGUAGE plpgsql\n"
    "        SECURITY DEFINER\n"
    "        SET search_path = pg_catalog\n"
    "        AS $$\n"
    "        DECLARE\n"
    "          bound_tenant_id uuid;\n"
    "          bound_agent_id uuid;\n"
    "          authority_ok boolean := FALSE;\n"
    "        BEGIN\n"
    "          IF TG_OP='UPDATE' AND (\n"
    "            OLD.tenant_id IS DISTINCT FROM NEW.tenant_id\n"
    "            OR OLD.session_id IS DISTINCT FROM NEW.session_id\n"
    "          ) THEN\n"
    "            RAISE EXCEPTION 'session_v2_authority_frame_immutable' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          SELECT tenant_id,agent_id INTO bound_tenant_id,bound_agent_id\n"
    "          FROM public.chat_sessions WHERE id=NEW.session_id;\n"
    "          IF NOT FOUND OR NEW.tenant_id IS DISTINCT FROM bound_tenant_id THEN\n"
    "            RAISE EXCEPTION 'session_v2_tenant_binding_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          IF TG_TABLE_NAME='session_event_cursors' THEN\n"
    "            SELECT (TRUE) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_event_outbox' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS event\n"
    "          WHERE event.id=NEW.event_id\n"
    "            AND event.tenant_id=NEW.tenant_id\n"
    "            AND event.session_id=NEW.session_id\n"
    "            AND event.sequence=NEW.sequence\n"
    "        )) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_commands' THEN\n"
    "            SELECT (NEW.causation_command_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.session_commands AS cause\n"
    "          WHERE cause.id=NEW.causation_command_id\n"
    "            AND cause.tenant_id=NEW.tenant_id\n"
    "            AND cause.session_id=NEW.session_id\n"
    "        )) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_turn_inputs' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.session_commands AS command\n"
    "          WHERE command.id=NEW.command_id\n"
    "            AND command.tenant_id=NEW.tenant_id\n"
    "            AND command.session_id=NEW.session_id\n"
    "        )\n"
    "        AND (NEW.target_run_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.target_run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        ))\n"
    "        AND (NEW.request_item_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS request_event\n"
    "          WHERE request_event.item_id=NEW.request_item_id\n"
    "            AND request_event.tenant_id=NEW.tenant_id\n"
    "            AND request_event.session_id=NEW.session_id\n"
    "        ))\n"
    "        AND (NEW.fork_after_sequence IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS fork_event\n"
    "          WHERE fork_event.sequence=NEW.fork_after_sequence\n"
    "            AND fork_event.tenant_id=NEW.tenant_id\n"
    "            AND fork_event.session_id=NEW.session_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_input_admissions' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1\n"
    "          FROM public.session_commands AS command\n"
    "          JOIN public.session_turn_inputs AS turn_input\n"
    "            ON turn_input.id=NEW.input_id\n"
    "           AND turn_input.command_id=command.id\n"
    "           AND turn_input.tenant_id=command.tenant_id\n"
    "           AND turn_input.session_id=command.session_id\n"
    "          WHERE command.id=NEW.command_id\n"
    "            AND command.tenant_id=NEW.tenant_id\n"
    "            AND command.session_id=NEW.session_id\n"
    "        )\n"
    "        AND (NEW.hook_item_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS hook_event\n"
    "          WHERE hook_event.item_id=NEW.hook_item_id\n"
    "            AND hook_event.tenant_id=NEW.tenant_id\n"
    "            AND hook_event.session_id=NEW.session_id\n"
    "            AND hook_event.item_kind='hook'\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_carry_forwards' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1\n"
    "          FROM public.session_input_admissions AS admission\n"
    "          JOIN public.session_turn_inputs AS turn_input\n"
    "            ON turn_input.id=admission.input_id\n"
    "           AND turn_input.tenant_id=admission.tenant_id\n"
    "           AND turn_input.session_id=admission.session_id\n"
    "          WHERE admission.id=NEW.source_admission_id\n"
    "            AND admission.input_id=NEW.source_input_id\n"
    "            AND admission.hook_run_id=NEW.source_hook_run_id\n"
    "            AND admission.tenant_id=NEW.tenant_id\n"
    "            AND admission.session_id=NEW.session_id\n"
    "        )\n"
    "        AND (NEW.target_turn_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS target_result\n"
    "          WHERE target_result.tenant_id=NEW.tenant_id\n"
    "            AND target_result.session_id=NEW.session_id\n"
    "            AND target_result.turn_id=NEW.target_turn_id\n"
    "        ) OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS target_event\n"
    "          WHERE target_event.tenant_id=NEW.tenant_id\n"
    "            AND target_event.session_id=NEW.session_id\n"
    "            AND target_event.scope_json->>'turn_id'=NEW.target_turn_id\n"
    "        ))\n"
    "        AND (NEW.target_round_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS target_result\n"
    "          WHERE target_result.tenant_id=NEW.tenant_id\n"
    "            AND target_result.session_id=NEW.session_id\n"
    "            AND target_result.turn_id=NEW.target_turn_id\n"
    "            AND target_result.round_id=NEW.target_round_id\n"
    "        ))\n"
    "        AND (NEW.consumed_event_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS consumed_event\n"
    "          WHERE consumed_event.id=NEW.consumed_event_id\n"
    "            AND consumed_event.item_id=NEW.context_source_item_id\n"
    "            AND consumed_event.tenant_id=NEW.tenant_id\n"
    "            AND consumed_event.session_id=NEW.session_id\n"
    "            AND consumed_event.scope_json->>'turn_id'=NEW.target_turn_id\n"
    "            AND consumed_event.scope_json->>'round_id'=NEW.target_round_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_control_inputs' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.session_commands AS command\n"
    "          WHERE command.id=NEW.command_id\n"
    "            AND command.tenant_id=NEW.tenant_id\n"
    "            AND command.session_id=NEW.session_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.expected_run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        )\n"
    "        AND (NEW.request_item_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS request_event\n"
    "          WHERE request_event.item_id=NEW.request_item_id\n"
    "            AND request_event.tenant_id=NEW.tenant_id\n"
    "            AND request_event.session_id=NEW.session_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_turn_replacements' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1\n"
    "          FROM public.session_commands AS saga_command\n"
    "          JOIN public.session_commands AS parent_command\n"
    "            ON parent_command.id=saga_command.causation_command_id\n"
    "           AND parent_command.tenant_id=saga_command.tenant_id\n"
    "           AND parent_command.session_id=saga_command.session_id\n"
    "          JOIN public.session_commands AS cancel_command\n"
    "            ON cancel_command.id=NEW.cancel_command_id\n"
    "           AND cancel_command.causation_command_id=saga_command.id\n"
    "           AND cancel_command.tenant_id=saga_command.tenant_id\n"
    "           AND cancel_command.session_id=saga_command.session_id\n"
    "          JOIN public.session_turn_inputs AS replacement_input\n"
    "            ON replacement_input.id=NEW.replacement_input_id\n"
    "           AND replacement_input.command_id=parent_command.id\n"
    "           AND replacement_input.tenant_id=saga_command.tenant_id\n"
    "           AND replacement_input.session_id=saga_command.session_id\n"
    "          JOIN public.session_input_admissions AS admission\n"
    "            ON admission.input_id=replacement_input.id\n"
    "           AND admission.command_id=parent_command.id\n"
    "           AND admission.tenant_id=saga_command.tenant_id\n"
    "           AND admission.session_id=saga_command.session_id\n"
    "          JOIN public.session_control_inputs AS cancel_control\n"
    "            ON cancel_control.id=NEW.cancel_control_id\n"
    "           AND cancel_control.command_id=cancel_command.id\n"
    "           AND cancel_control.expected_run_id=NEW.old_run_id\n"
    "           AND cancel_control.tenant_id=saga_command.tenant_id\n"
    "           AND cancel_control.session_id=saga_command.session_id\n"
    "          WHERE saga_command.id=NEW.command_id\n"
    "            AND saga_command.namespace='turn_replacement'\n"
    "            AND cancel_command.namespace='control_input'\n"
    "            AND parent_command.namespace='human_input'\n"
    "            AND parent_command.command_kind='interrupt_and_replace'\n"
    "            AND replacement_input.intent='interrupt_and_replace'\n"
    "            AND replacement_input.target_turn_id=NEW.old_turn_id\n"
    "            AND replacement_input.target_run_id=NEW.old_run_id\n"
    "            AND admission.state='admitted'\n"
    "            AND saga_command.tenant_id=NEW.tenant_id\n"
    "            AND saga_command.session_id=NEW.session_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS old_run\n"
    "          WHERE old_run.id=NEW.old_run_id\n"
    "            AND old_run.tenant_id=NEW.tenant_id\n"
    "            AND old_run.parent_session_id=NEW.session_id::text\n"
    "            AND old_run.parent_agent_id=bound_agent_id\n"
    "            AND COALESCE(\n"
    "                  NULLIF(old_run.metadata_json->>'turn_id',''),\n"
    "                  'turn-' || replace(old_run.id::text,'-','')\n"
    "                )=NEW.old_turn_id\n"
    "        )\n"
    "        AND (NEW.last_event_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS last_event\n"
    "          WHERE last_event.id=NEW.last_event_id\n"
    "            AND last_event.tenant_id=NEW.tenant_id\n"
    "            AND last_event.session_id=NEW.session_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_tool_invocations' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS result\n"
    "          WHERE result.tenant_id=NEW.tenant_id\n"
    "            AND result.session_id=NEW.session_id\n"
    "            AND result.run_id=NEW.run_id\n"
    "            AND result.round_id=NEW.round_id\n"
    "        )\n"
    "        AND (NEW.result_event_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS result_event\n"
    "          WHERE result_event.id=NEW.result_event_id\n"
    "            AND result_event.item_kind='tool_result'\n"
    "            AND result_event.lifecycle='completed'\n"
    "            AND result_event.invocation_id=NEW.id\n"
    "            AND result_event.provider_tool_use_id=NEW.provider_tool_use_id\n"
    "            AND result_event.tenant_id=NEW.tenant_id\n"
    "            AND result_event.session_id=NEW.session_id\n"
    "            AND result_event.run_id=NEW.run_id\n"
    "            AND result_event.scope_json->>'round_id'=NEW.round_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_model_results' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "            AND COALESCE(\n"
    "                  NULLIF(run.metadata_json->>'turn_id',''),\n"
    "                  'turn-' || replace(run.id::text,'-','')\n"
    "                )=NEW.turn_id\n"
    "        )\n"
    "        AND jsonb_typeof(NEW.bound_input_ids_json)='array'\n"
    "        AND NOT EXISTS (\n"
    "          SELECT 1\n"
    "          FROM jsonb_array_elements_text(NEW.bound_input_ids_json) AS input_ref(value)\n"
    "          LEFT JOIN public.session_turn_inputs AS bound_input\n"
    "            ON bound_input.id=CASE\n"
    "                 WHEN input_ref.value ~* "
    "'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'\n"
    "                 THEN input_ref.value::uuid\n"
    "               END\n"
    "           AND bound_input.tenant_id=NEW.tenant_id\n"
    "           AND bound_input.session_id=NEW.session_id\n"
    "          WHERE bound_input.id IS NULL\n"
    "        )\n"
    "        AND (NEW.round_committed_event_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS commit_event\n"
    "          WHERE commit_event.id=NEW.round_committed_event_id\n"
    "            AND commit_event.result_id=NEW.id\n"
    "            AND commit_event.tenant_id=NEW.tenant_id\n"
    "            AND commit_event.session_id=NEW.session_id\n"
    "            AND commit_event.run_id=NEW.run_id\n"
    "            AND commit_event.scope_json->>'turn_id'=NEW.turn_id\n"
    "            AND commit_event.scope_json->>'round_id'=NEW.round_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_round_obligations' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS source_result\n"
    "          WHERE source_result.id=NEW.source_result_id\n"
    "            AND source_result.tenant_id=NEW.tenant_id\n"
    "            AND source_result.session_id=NEW.session_id\n"
    "            AND source_result.run_id=NEW.run_id\n"
    "            AND source_result.turn_id=NEW.turn_id\n"
    "        )) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_next_round_plans' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS source_result\n"
    "          WHERE source_result.id=NEW.source_result_id\n"
    "            AND source_result.tenant_id=NEW.tenant_id\n"
    "            AND source_result.session_id=NEW.session_id\n"
    "            AND source_result.run_id=NEW.run_id\n"
    "        )\n"
    "        AND jsonb_typeof(NEW.obligation_ids_json)='array'\n"
    "        AND NOT EXISTS (\n"
    "          SELECT 1\n"
    "          FROM jsonb_array_elements_text(NEW.obligation_ids_json) AS obligation_ref(value)\n"
    "          LEFT JOIN public.session_round_obligations AS obligation\n"
    "            ON obligation.id=CASE\n"
    "                 WHEN obligation_ref.value ~* "
    "'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'\n"
    "                 THEN obligation_ref.value::uuid\n"
    "               END\n"
    "           AND obligation.tenant_id=NEW.tenant_id\n"
    "           AND obligation.session_id=NEW.session_id\n"
    "           AND obligation.run_id=NEW.run_id\n"
    "           AND obligation.source_result_id=NEW.source_result_id\n"
    "          WHERE obligation.id IS NULL\n"
    "        )) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_run_outcomes' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.runtime_tasks AS run\n"
    "          WHERE run.id=NEW.run_id\n"
    "            AND run.tenant_id=NEW.tenant_id\n"
    "            AND run.parent_session_id=NEW.session_id::text\n"
    "            AND run.parent_agent_id=bound_agent_id\n"
    "        )\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS terminal_result\n"
    "          WHERE terminal_result.id=NEW.terminal_result_id\n"
    "            AND terminal_result.tenant_id=NEW.tenant_id\n"
    "            AND terminal_result.session_id=NEW.session_id\n"
    "            AND terminal_result.run_id=NEW.run_id\n"
    "            AND terminal_result.turn_id=NEW.turn_id\n"
    "        )\n"
    "        AND (NEW.terminal_event_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS terminal_event\n"
    "          WHERE terminal_event.id=NEW.terminal_event_id\n"
    "            AND terminal_event.result_id=NEW.terminal_result_id\n"
    "            AND terminal_event.tenant_id=NEW.tenant_id\n"
    "            AND terminal_event.session_id=NEW.session_id\n"
    "            AND terminal_event.run_id=NEW.run_id\n"
    "            AND terminal_event.scope_json->>'turn_id'=NEW.turn_id\n"
    "        ))) INTO authority_ok;\n"
    "          ELSIF TG_TABLE_NAME='session_feedback_aggregates' THEN\n"
    "            SELECT (EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS target_event\n"
    "          WHERE target_event.item_id=NEW.target_item_id\n"
    "            AND target_event.tenant_id=NEW.tenant_id\n"
    "            AND target_event.session_id=NEW.session_id\n"
    "            AND (NEW.target_result_id IS NULL OR target_event.result_id=NEW.target_result_id)\n"
    "        )\n"
    "        AND (NEW.target_result_id IS NULL OR EXISTS (\n"
    "          SELECT 1 FROM public.session_model_results AS target_result\n"
    "          WHERE target_result.id=NEW.target_result_id\n"
    "            AND target_result.tenant_id=NEW.tenant_id\n"
    "            AND target_result.session_id=NEW.session_id\n"
    "        ))\n"
    "        AND EXISTS (\n"
    "          SELECT 1 FROM public.chat_transcript_events AS mutation_event\n"
    "          WHERE mutation_event.item_id=NEW.last_mutation_item_id\n"
    "            AND mutation_event.item_kind='evaluation_feedback_mutation'\n"
    "            AND mutation_event.tenant_id=NEW.tenant_id\n"
    "            AND mutation_event.session_id=NEW.session_id\n"
    "        )) INTO authority_ok;\n"
    "          ELSE\n"
    "            authority_ok := FALSE;\n"
    "          END IF;\n"
    "          IF NOT COALESCE(authority_ok,FALSE) THEN\n"
    "            RAISE EXCEPTION 'session_v2_authority_binding_mismatch' USING ERRCODE='23514';\n"
    "          END IF;\n"
    "          RETURN NEW;\n"
    "        END;\n"
    "        $$\n"
    "    "
)


def build_session_event_contract_function_sql() -> str:
    return _SESSION_EVENT_CONTRACT_FUNCTION_SQL


def build_session_writer_epoch_function_sql() -> str:
    return _SESSION_WRITER_EPOCH_FUNCTION_SQL


def build_session_tenant_binding_function_sql() -> str:
    return _SESSION_TENANT_BINDING_FUNCTION_SQL
